### ISSUE TITLE
Errors in merged ref index: no BUS records

### ISSUE THREAD

**Issue by gabriellayi** [pachterlab/kb_python#101]
**Describe the issue**
Hi,

I'm learning how to use kallisto to generate loom files and then run scvelo.
I'm working on mouse genome, so I followed a tutorial from kb to build the index, I split the intron into 8 parts, and then I put all the parts of the index of the intron to preprocess my samples.

**What is the exact command that was run?**
```
!kb count --loom -i index.idx,index.idx_intron.6,index.idx_intron.5,index.idx_intron.4,index.idx_intron.3,index.idx_intron.2,index.idx_intron.1,index.idx_intron.0,index.idx_cdna -g t2g.txt -x 10xv3 -o AIRE_GW_Het_fastqs
-c1 cdna_t2c.txt -c2 intron_t2c.txt --workflow lamanno --filter bustools
AIRE_GW_Het_S27_L004_R1_001.fastq.gz
AIRE_GW_Het_S27_L004_R2_001.fastq.gz
```

**Command output (with `--verbose` flag)**
```
[2021-03-01 08:36:41,313] WARNING Multiple indices were provided. Aligning to split indices is currently EXPERIMENTAL and results in loss of reads. It is recommended to use a single index until this feature is fully supported. Use at your own risk!
[2021-03-01 08:36:41,313] INFO Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite.
[2021-03-01 08:36:41,313] INFO Sorting BUS file AIRE_GW_Het_fastqs/output.bus to AIRE_GW_Het_fastqs/tmp/output.s.bus
[2021-03-01 08:38:33,678] INFO Whitelist not provided
[2021-03-01 08:38:33,678] INFO Copying pre-packaged 10XV3 whitelist to AIRE_GW_Het_fastqs
[2021-03-01 08:38:34,318] INFO Inspecting BUS file AIRE_GW_Het_fastqs/tmp/output.s.bus
[2021-03-01 08:39:07,192] INFO Correcting BUS records in AIRE_GW_Het_fastqs/tmp/output.s.bus to AIRE_GW_Het_fastqs/tmp/output.s.c.bus with whitelist AIRE_GW_Het_fastqs/10xv3_whitelist.txt
[2021-03-01 08:39:46,125] INFO Sorting BUS file AIRE_GW_Het_fastqs/tmp/output.s.c.bus to AIRE_GW_Het_fastqs/output.unfiltered.bus
[2021-03-01 08:40:33,482] INFO Capturing records from BUS file AIRE_GW_Het_fastqs/output.unfiltered.bus to AIRE_GW_Het_fastqs/tmp/spliced.bus with capture list intron_t2c.txt
[2021-03-01 08:41:06,922] INFO Sorting BUS file AIRE_GW_Het_fastqs/tmp/spliced.bus to AIRE_GW_Het_fastqs/spliced.unfiltered.bus
[2021-03-01 08:41:46,465] INFO Inspecting BUS file AIRE_GW_Het_fastqs/spliced.unfiltered.bus
[2021-03-01 08:42:18,782] INFO Generating count matrix AIRE_GW_Het_fastqs/counts_unfiltered/spliced from BUS file AIRE_GW_Het_fastqs/spliced.unfiltered.bus
[2021-03-01 08:42:58,084] INFO Capturing records from BUS file AIRE_GW_Het_fastqs/output.unfiltered.bus to AIRE_GW_Het_fastqs/tmp/unspliced.bus with capture list cdna_t2c.txt
[2021-03-01 08:43:04,782] ERROR An exception occurred
Traceback (most recent call last):
File "/Users/Yi/opt/anaconda3/lib/python3.8/site-packages/kb_python/main.py", line 837, in main
COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
File "/Users/Yi/opt/anaconda3/lib/python3.8/site-packages/kb_python/main.py", line 197, in parse_count
count_velocity(
File "/Users/Yi/opt/anaconda3/lib/python3.8/site-packages/kb_python/count.py", line 1567, in count_velocity
capture_result = bustools_capture(
File "/Users/Yi/opt/anaconda3/lib/python3.8/site-packages/kb_python/validate.py", line 124, in inner
validate(arg)
File "/Users/Yi/opt/anaconda3/lib/python3.8/site-packages/kb_python/validate.py", line 85, in validate
VALIDATORSext
File "/Users/Yi/opt/anaconda3/lib/python3.8/site-packages/kb_python/validate.py", line 40, in validate_bus
raise FileVerificationFailed('{} has no BUS records'.format(path))
kb_python.validate.FileVerificationFailed: AIRE_GW_Het_fastqs/tmp/unspliced.bus has no BUS records
```
I also tried to generate one index for the intron, however, the code was running for over 72h that I had to kill it.

Could you please give me some suggestions?

Thank you so much in advance!

Best,
Yi

**Comment by Lioscro** [comment]
Hi, @gabriellayi,
As you may notice in the output, using split indices isn't fully supported (yet), and the number of reads that may be lost becomes larger the more splits you introduce.
My first suggestion would be to use the full index (which it seems like you did but was running for too long), but an alternative is to use less splits, perhaps 2 or 4.
