### ISSUE TITLE
Error in kb ref (unexpected keyword argument)

### ISSUE THREAD

**Issue by cbligaard** [pachterlab/kb_python#132]
**Describe the issue**
Hi kb-python team, 

I am having an issue with kb ref, which fails due to an "unexpected keyword argument". I installed the program today using pip. The issue arises both on a server and my local computer.

**What is the exact command that was run?**
```
kb ref -i transcriptome.idx -g transcripts_to_genes.txt -f1 cdna.fa --verbose Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz Homo_sapiens.GRCh38.104.gtf.gz
```

**Command output (with `--verbose` flag)**
```
/usr/local/lib/python3.7/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
[2021-06-09 22:32:56,883]   DEBUG [main] Printing verbose output
[2021-06-09 22:32:56,884]   DEBUG [main] kallisto binary located at /usr/local/lib/python3.7/site-packages/kb_python/bins/darwin/kallisto/kallisto
[2021-06-09 22:32:56,884]   DEBUG [main] bustools binary located at /usr/local/lib/python3.7/site-packages/kb_python/bins/darwin/bustools/bustools
[2021-06-09 22:32:56,884]   DEBUG [main] Creating `tmp` directory
[2021-06-09 22:32:56,884]   DEBUG [main] Namespace(bustools='/usr/local/lib/python3.7/site-packages/kb_python/bins/darwin/bustools/bustools', c1=None, c2=None, command='ref', d=None, f1='cdna.fa', f2=None, fasta='Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz', feature=None, flank=None, g='transcripts_to_genes.txt', gtf='Homo_sapiens.GRCh38.104.gtf.gz', i='transcriptome.idx', k=None, kallisto='/usr/local/lib/python3.7/site-packages/kb_python/bins/darwin/kallisto/kallisto', keep_tmp=False, list=False, n=1, no_mismatches=False, overwrite=False, tmp=None, verbose=True, workflow='standard')
[2021-06-09 22:32:56,884]    INFO [ref] Preparing Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz, Homo_sapiens.GRCh38.104.gtf.gz
[2021-06-09 22:34:17,189]    INFO [ref] Splitting genome Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz into cDNA at /Users/user/Downloads/tmp/tmpmogjfllg
[2021-06-09 22:35:55,403]    INFO [ref] Concatenating 1 cDNAs to cdna.fa
[2021-06-09 22:35:55,403]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kb_python/main.py", line 853, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/usr/local/lib/python3.7/site-packages/kb_python/main.py", line 177, in parse_ref
    temp_dir=temp_dir
  File "/usr/local/lib/python3.7/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kb_python/ref.py", line 409, in ref
    *cdnas, out_path=cdna_path, temp_dir=temp_dir
TypeError: concatenate_files_as_text() got an unexpected keyword argument 'temp_dir'
[2021-06-09 22:35:55,949]   DEBUG [main] Removing `tmp` directory

```

**Comment by Lioscro** [comment]
Hi, @cbligaard,
Thanks for the report. Must have been some leftover keywords from the previous refactor.
This should be fixed in version 0.26.3
