### ISSUE TITLE
kb count AttributeError: 'Namespace' object has no attribute 'nucleus'

### ISSUE THREAD

**Issue by cbligaard** [pachterlab/kb_python#133]
**Describe the issue**
Hi kb-python team,
I have an issue with kb count, which occurs quickly after start-up in version 0.26.2. 

**What is the exact command that was run?**
```
kb count -i  refs/transcriptome.idx -g refs/transcripts_to_genes.txt -x SMARTSEQ --h5ad -t 2 --verbose data/file_R1.fq.gz data/file_R2.fq.gz
```

**Command output (with `--verbose` flag)**
```
[2021-06-10 13:13:35,089]   DEBUG [main] Printing verbose output
[2021-06-10 13:13:35,091]   DEBUG [main] kallisto binary located at /usr/local/lib/python3.8/site-packages/kb_python/bins/linux/kallisto/kallisto
[2021-06-10 13:13:35,091]   DEBUG [main] bustools binary located at /usr/local/lib/python3.8/site-packages/kb_python/bins/linux/bustools/bustools
[2021-06-10 13:13:35,092]   DEBUG [main] Creating `./tmp` directory
[2021-06-10 13:13:35,094]   DEBUG [main] Namespace(bustools='/usr/local/lib/python3.8/site-packages/kb_python/bins/linux/bustools/bustools', c1=None, c2=None, cellranger=False, command='count', dry_run=False, fastqs=['data/file_R1.fq.gz', 'data/file_R2.fq.gz'], filter=None, g='refs/transcripts_to_genes.txt', h5ad=True, i='refs/transcriptome.idx', kallisto='/usr/local/lib/python3.8/site-packages/kb_python/bins/linux/kallisto/kallisto', keep_tmp=False, list=False, loom=False, m='4G', mm=False, no_inspect=False, no_validate=False, o='.', overwrite=False, report=False, t=2, tcc=False, tmp=None, verbose=True, w=None, workflow='standard', x='SMARTSEQ')
[2021-06-10 13:13:35,094]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kb_python/main.py", line 853, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/usr/local/lib/python3.8/site-packages/kb_python/main.py", line 252, in parse_count
    if getattr(args, arg):
AttributeError: 'Namespace' object has no attribute 'nucleus'
[2021-06-10 13:13:35,094]   DEBUG [main] Removing `./tmp` directory

```

**Comment by Lioscro** [comment]
Hi, @cbligaard,
This should be fixed in version 0.26.3
