### ISSUE TITLE
error in writing transcript_ids for tcc h5ad

### ISSUE THREAD

**Issue by nmarkari** [pachterlab/kb_python#141]
**Describe the issue**
At the final step of writing to the h5ad file, kb has an error in writing the transcript_ids

**What is the exact command that was run?**
```
kb count -tcc -i ../../data/ref/index.idx -g ../../data/ref/t2g.txt -x 10xv2 -o ../../data/preprocessed/Yao/10x/ACA -t 16 --h5ad ../../data/raw/Yao/10x/ACA/*/*R*
```

**Command output (with `--verbose` flag)**
```
[2021-07-13 14:59:12,505]   DEBUG [main] Printing verbose output
[2021-07-13 14:59:12,505]   DEBUG [main] kallisto binary located at /home/nmarkari/.local/lib/python3.6/
site-packages/kb_python/bins/linux/kallisto/kallisto
[2021-07-13 14:59:12,505]   DEBUG [main] bustools binary located at /home/nmarkari/.local/lib/python3.6/
site-packages/kb_python/bins/linux/bustools/bustools
[2021-07-13 14:59:12,505]   DEBUG [main] Creating `../../data/preprocessed/Yao/10x/ACA/tmp` directory
[2021-07-13 14:59:12,505]   DEBUG [main] Namespace(bustools='/home/nmarkari/.local/lib/python3.6/site-pa
ckages/kb_python/bins/linux/bustools/bustools', c1=None, c2=None, cellranger=False, command='count', dry
_run=False, fastqs=['../../data/raw/Yao/10x/ACA/L8TX_180406_01_C06/L8TX_180406_01_C06_R1.fastq', '../../
data/raw/Yao/10x/ACA/L8TX_180406_01_C06/L8TX_180406_01_C06_R2.fastq'], filter=None, g='../../data/ref/t2
g.txt', h5ad=True, i='../../data/ref/index.idx', kallisto='/home/nmarkari/.local/lib/python3.6/site-pack
ages/kb_python/bins/linux/kallisto/kallisto', keep_tmp=False, list=False, loom=False, m='4G', mm=False, 
no_inspect=False, no_validate=False, o='../../data/preprocessed/Yao/10x/ACA', overwrite=False, report=Fa
lse, t=16, tcc=True, tmp=None, verbose=True, w=None, workflow='standard', x='10xv2')
[2021-07-13 14:59:12,549]    INFO [count] Skipping kallisto bus because output files already exist. Use 
the --overwrite flag to overwrite.
[2021-07-13 14:59:12,549]    INFO [count] Sorting BUS file ../../data/preprocessed/Yao/10x/ACA/output.bu
s to ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.bus
[2021-07-13 14:59:12,549]   DEBUG [count] bustools sort -o ../../data/preprocessed/Yao/10x/ACA/tmp/outpu
t.s.bus -T ../../data/preprocessed/Yao/10x/ACA/tmp -t 16 -m 4G ../../data/preprocessed/Yao/10x/ACA/outpu
t.bus
[2021-07-13 15:01:09,048]   DEBUG [count] Read in 364934604 BUS records
[2021-07-13 15:01:19,280]   DEBUG [count] ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.bus passed va
lidation
[2021-07-13 15:01:19,281]    INFO [count] Whitelist not provided
[2021-07-13 15:01:19,281]    INFO [count] Copying pre-packaged 10XV2 whitelist to ../../data/preprocesse
d/Yao/10x/ACA
[2021-07-13 15:01:19,376]    INFO [count] Inspecting BUS file ../../data/preprocessed/Yao/10x/ACA/tmp/ou
tput.s.bus
[2021-07-13 15:01:19,376]   DEBUG [count] bustools inspect -o ../../data/preprocessed/Yao/10x/ACA/inspec
t.json -w ../../data/preprocessed/Yao/10x/ACA/10x_version2_whitelist.txt -e ../../data/preprocessed/Yao/
10x/ACA/matrix.ec ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.bus
[2021-07-13 15:01:49,614]    INFO [count] Correcting BUS records in ../../data/preprocessed/Yao/10x/ACA/
tmp/output.s.bus to ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.c.bus with whitelist ../../data/pre
processed/Yao/10x/ACA/10x_version2_whitelist.txt
[2021-07-13 15:01:49,614]   DEBUG [count] bustools correct -o ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.c.bus -w ../../data/preprocessed/Yao/10x/ACA/10x_version2_whitelist.txt ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.bus
[2021-07-13 15:02:07,467]   DEBUG [count] Found 737280 barcodes in the whitelist
[2021-07-13 15:02:07,467]   DEBUG [count] Processed 161087141 BUS records
[2021-07-13 15:02:07,467]   DEBUG [count] In whitelist = 153524201
[2021-07-13 15:02:07,467]   DEBUG [count] Corrected    = 2266967
[2021-07-13 15:02:07,467]   DEBUG [count] Uncorrected  = 5295973
[2021-07-13 15:02:17,733]   DEBUG [count] ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.c.bus passed validation
[2021-07-13 15:02:17,734]    INFO [count] Sorting BUS file ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.c.bus to ../../data/preprocessed/Yao/10x/ACA/output.unfiltered.bus
[2021-07-13 15:02:17,734]   DEBUG [count] bustools sort -o ../../data/preprocessed/Yao/10x/ACA/output.unfiltered.bus -T ../../data/preprocessed/Yao/10x/ACA/tmp -t 16 -m 4G ../../data/preprocessed/Yao/10x/ACA/tmp/output.s.c.bus
[2021-07-13 15:03:12,489]   DEBUG [count] Read in 155791168 BUS records
[2021-07-13 15:03:21,981]   DEBUG [count] ../../data/preprocessed/Yao/10x/ACA/output.unfiltered.bus passed validation
[2021-07-13 15:03:21,982]    INFO [count] Generating count matrix ../../data/preprocessed/Yao/10x/ACA/counts_unfiltered/cells_x_tcc from BUS file ../../data/preprocessed/Yao/10x/ACA/output.unfiltered.bus
[2021-07-13 15:03:21,982]   DEBUG [count] bustools count -o ../../data/preprocessed/Yao/10x/ACA/counts_unfiltered/cells_x_tcc -g ../../data/ref/t2g.txt -e ../../data/preprocessed/Yao/10x/ACA/matrix.ec -t ../../data/preprocessed/Yao/10x/ACA/transcripts.txt ../../data/preprocessed/Yao/10x/ACA/output.unfiltered.bus
[2021-07-13 15:06:39,928]   DEBUG [count] ../../data/preprocessed/Yao/10x/ACA/counts_unfiltered/cells_x_tcc.mtx passed validation
[2021-07-13 15:06:39,928]    INFO [count] Reading matrix ../../data/preprocessed/Yao/10x/ACA/counts_unfiltered/cells_x_tcc.mtx
[2021-07-13 15:09:46,790]    INFO [count] Writing matrix to h5ad ../../data/preprocessed/Yao/10x/ACA/counts_unfiltered/adata.h5ad
[2021-07-13 15:09:52,396]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 274, in write_series
    **dataset_kwargs,
  File "/home/nmarkari/.local/lib/python3.6/site-packages/h5py/_hl/group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 140, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)   
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 443, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 94, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 248, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 263, in write_dataframe
    write_series(group, col_name, series, dataset_kwargs=dataset_kwargs)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/utils.py", line 216, in func_wrapper
    ) from e
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'transcript_ids' of <class 'h5py._hl.group.Group'> from /.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nmarkari/.local/lib/python3.6/site-packages/kb_python/main.py", line 856, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/kb_python/main.py", line 341, in parse_count
    temp_dir=temp_dir
  File "/home/nmarkari/.local/lib/python3.6/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/kb_python/count.py", line 1230, in count
    threads=threads
  File "/home/nmarkari/.local/lib/python3.6/site-packages/kb_python/count.py", line 710, in convert_matrix
    adata.write(h5ad_path)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_core/anndata.py", line 1911, in write_h5ad
    as_dense=as_dense,
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 112, in write_h5ad
    write_attribute(f, "var", adata.var, dataset_kwargs=dataset_kwargs)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/home/nmarkari/.local/lib/python3.6/site-packages/anndata/_io/utils.py", line 216, in func_wrapper
    ) from e
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'transcript_ids' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'var' of <class 'h5py._hl.files.File'> from /.
[2021-07-13 15:09:52,398]   DEBUG [main] Removing `../../data/preprocessed/Yao/10x/ACA/tmp` directory
```

**Comment by Lioscro** [comment]
Hi, @nmarkari,

It seems like h5py doesn't want to write columns with lists (which is what the `transcript_ids` column contains). May I ask what version of anndata and h5py you are using?
I've noticed that there are problems like this when using a certain version of h5py.
You can check the versions by running `pip show h5py` and `pip show anndata`

**Comment by nmarkari** [comment]
@Lioscro Version 0.7.6 of anndata and version 3.1.0 of h5py. Which versions would you suggest using?

**Comment by Lioscro** [comment]
Ah, that makes sense.
Any version of h5py < 3 should work fine.
I'm starting to think we should just output the column as a delimited string so that this isn't a issue with newer h5py versions...
