### ISSUE TITLE
Error: unspliced.bus has no BUS records

### ISSUE THREAD

**Issue by yzhou666** [pachterlab/kb_python#148]
Hi! I was following the Seurat to Velocity tutorial(https://github.com/basilkhuder/Seurat-to-RNA-Velocity) and is trying to set up the kallisto reference and index for RNA velocity analysis. I was able to complete the reference but kept running into error when trying to create the loom file. 

Here is the line of code to create the reference: 
kb ref -i index.idx -g t2g.txt -f1 cdna.fa -f2 intron.fa -c1 cdna_t2c.txt -c2 intron_t2c.txt --workflow lamanno -n 4 \
Mus_musculus.GRCm39.dna.primary_assembly.fa \ Mus_musculus.GRCm39.104.gtf

Here is the line of code to create the loom file:
kb count -i ref/index.idx_cdna -g ref/t2g.txt -x 10xv2 -o sample_1 \ -c1 ref/cdna_t2c.txt -c2 ref/intron_t2c.txt --loom --filter bustools -t 2 --workflow lamanno 
\SN-LD-CD45pos-MC2_S8_L001_I1_001.fastq.gz 
\SN-LD-CD45pos-MC2_S8_L001_R1_001.fastq.gz 
\SN-LD-CD45pos-MC2_S8_L001_R2_001.fastq.gz 
\SN-LD-CD45pos-MC2_S8_L002_I1_001.fastq.gz 
\SN-LD-CD45pos-MC2_S8_L002_R1_001.fastq.gz 
\SN-LD-CD45pos-MC2_S8_L002_R2_001.fastq.gz

Here is the output:
[2021-10-07 11:48:02,811]    INFO [count_lamanno] Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite. 
[2021-10-07 11:48:02,815]    INFO [count_lamanno] Sorting BUS file sample_1/output.bus to sample_1/tmp/output.s.bus
[2021-10-07 11:49:18,362]    INFO [count_lamanno] Whitelist not provided
[2021-10-07 11:49:18,364]    INFO [count_lamanno] Copying pre-packaged 10XV2 whitelist to sample_1
[2021-10-07 11:49:18,787]    INFO [count_lamanno] Inspecting BUS file sample_1/tmp/output.s.bus
[2021-10-07 11:49:25,679]    INFO [count_lamanno] Correcting BUS records in sample_1/tmp/output.s.bus to sample_1/tmp/output.s.c.bus with whitelist sample_1/10x_version2_whitelist.txt
[2021-10-07 11:49:35,058]    INFO [count_lamanno] Sorting BUS file sample_1/tmp/output.s.c.bus to sample_1/output.unfiltered.bus
[2021-10-07 11:49:46,497]    INFO [count_lamanno] Capturing records from BUS file sample_1/output.unfiltered.bus to sample_1/tmp/spliced.bus with capture list ref/intron_t2c.txt
[2021-10-07 11:49:50,388]    INFO [count_lamanno] Sorting BUS file sample_1/tmp/spliced.bus to sample_1/spliced.unfiltered.bus
[2021-10-07 11:50:01,785]    INFO [count_lamanno] Inspecting BUS file sample_1/spliced.unfiltered.bus
[2021-10-07 11:50:03,365]    INFO [count_lamanno] Generating count matrix sample_1/counts_unfiltered/spliced from BUS file sample_1/spliced.unfiltered.bus
[2021-10-07 11:50:08,219]    INFO [count_lamanno] Capturing records from BUS file sample_1/output.unfiltered.bus to sample_1/tmp/unspliced.bus with capture list ref/cdna_t2c.txt
[2021-10-07 11:50:11,902]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/kb_python/main.py", line 1326, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/usr/local/lib/python3.8/dist-packages/kb_python/main.py", line 446, in parse_count
    count_velocity(
  File "/usr/local/lib/python3.8/dist-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kb_python/count.py", line 1995, in count_velocity
    capture_result = bustools_capture(
  File "/usr/local/lib/python3.8/dist-packages/kb_python/validate.py", line 123, in inner
    validate(arg)
  File "/usr/local/lib/python3.8/dist-packages/kb_python/validate.py", line 85, in validate
    VALIDATORS[ext](path)
  File "/usr/local/lib/python3.8/dist-packages/kb_python/validate.py", line 40, in validate_bus
    raise ValidateError('{} has no BUS records'.format(path))
kb_python.validate.ValidateError: sample_1/tmp/unspliced.bus has no BUS records

Can you help with this issue? 

Thank you!

**Comment by Lioscro** [comment]
Hi, @yzhou666 
May I ask how much memory your system has and what version of `kb` you are running?
