### ISSUE TITLE
RNA Velocity Tutorial

### ISSUE THREAD

**Issue by nhutchins627** [pachterlab/kb_python#151]
Hi, I was really excited to try the kb python
 package especially to do RNA velocity but when I have tried to follow the tutorial steps (including using the data provided) I keep running into the same error:

I use the following command (after following the steps until that point without errors):
```
kb count --h5ad -i index.idx -g t2g.txt -x 10xv2 -o SRR6470906 -c1 spliced_t2c.txt -c2 unspliced_t2c.txt --workflow lamanno --filter bustools -t 2 -m 8Gb SRR6470906_S1_L001_R1_001.fastq.gz SRR6470906_S1_L001_R2_001.fastq.gz SRR6470906_S1_L002_R1_001.fastq.gz SRR6470906_S1_L002_R2_001.fastq.gz
```

But receive the following output:

```
[2021-11-19 12:14:59,418]    INFO [count_lamanno] Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite.
[2021-11-19 12:14:59,419]    INFO [count_lamanno] Sorting BUS file SRR6470906/output.bus to SRR6470906/tmp/output.s.bus
[2021-11-19 12:15:06,144]   ERROR [count_lamanno] Warning: low number supplied for maximum memory usage without M or G suffix
interpreting this as 8Gb
Read in 0 BUS records
[2021-11-19 12:15:06,145]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/main.py", line 1353, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/main.py", line 454, in parse_count
    count_velocity(
  File "/home/nicholas/.local/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/count.py", line 2009, in count_velocity
    sort_result = bustools_sort(
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/validate.py", line 116, in inner
    results = func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/count.py", line 478, in bustools_sort
    run_executable(command)
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.8/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/nicholas/.local/lib/python3.8/site-packages/kb_python/bins/linux/bustools/bustools sort -o SRR6470906/tmp/output.s.bus -T SRR6470906/tmp -t 2 -m 8Gb SRR6470906/output.bus' died with <Signals.SIGSEGV: 11>.

```

I was just wondering if you could help with what might be the issue?

**Comment by Lioscro** [comment]
Hi, @nhutchins627,
How much memory does your system have?
Also, could you post the command you used to generate the index?

**Comment by nhutchins627** [comment]
Thank you! I ended up being able to complete the tutorial. When I used --overwrite, it ran.
