### ISSUE TITLE
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

### ISSUE THREAD

**Issue by akhst7** [pachterlab/kb_python#156]
**Describe the issue**
A clear and concise description of what the issue is.
I tried to start kb and got an error with a following traceback.  I thought it was due to  `mistune` 2.0.1 that I update recently but it was not it.  I downgraded moisture to 2.0.0 but still getting the same error.   

**What is the exact command that was run?**
```
kb ref ...
```
**Command output (with `--verbose` flag)**
```
kb ref
Please copy and paste *VERBOSE* output here.
```
kb                                                                                                        07:50:48 PM
Traceback (most recent call last):
  File "/Volumes/Documents/Python/velocity/bin/kb", line 5, in <module>
    from kb_python.main import main
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/kb_python/main.py", line 24, in <module>
    from .count import count, count_smartseq, count_velocity
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/kb_python/count.py", line 48, in <module>
    from .report import render_report
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/kb_python/report.py", line 6, in <module>
    from nbconvert import HTMLExporter
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 23, in <module>
    from nbconvert.filters.highlight import Highlight2HTML
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/Volumes/Documents/Python/velocity/lib/python3.9/site-packages/nbconvert/filters/markdown_mistune.py", line 31, in <module>
    class MathBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar

**Comment by Lioscro** [comment]
This is most likely due to the `nbconvert` package. Could you try re-installing or downgrading?

**Comment by akhst7** [comment]
@Lioscro  Thanks. It worked.
