### ISSUE TITLE
kb count causing a SIGKILL

### ISSUE THREAD

**Issue by SimoniMD** [pachterlab/kb_python#157]
Hi!

I'm trying to create spliced and unspliced matrices to run velocyto (following [this tutorial](https://bustools.github.io/BUS_notebooks_R/velocity.html#download_data)), but i'm getting an error similar to [this issue](https://github.com/pachterlab/kb_python/issues/64). Unfortunately, i'm new to coding and i'm not sure I understand the solution posted. I tried adding a flag for half of the memory i have on my laptop, with `-m 8`, and it got the same error. I then tried using a server with more memory and got a similar issue.  

**What is the exact command that was run?**
```
kb count \
Endo_63_S1_L001_I2_001.fastq.gz \
Endo_63_S1_L002_R2_001.fastq.gz \
Endo_63_S1_L002_I1_001.fastq.gz \
Endo_63_S1_L002_I2_001.fastq.gz \
Endo_63_S1_L001_R1_001.fastq.gz \
Endo_63_S1_L001_I1_001.fastq.gz \
Endo_63_S1_L002_R1_001.fastq.gz \
Endo_63_S1_L001_R2_001.fastq.gz \
-i ~/Desktop/scRNA/CD45/DIY_method/hs_cDNA_introns.idx \
-x 10XV3 \
-g tr2g.tsv \ 
-c1 cDNA_tx_to_capture.txt \
-c2 introns_tx_to_capture.txt \ 
--workflow lamanno
```

and the output with the `--verbose` flag is...

**Command output (with `--verbose` flag)**
```
[2022-01-13 22:53:44,264]   DEBUG [count_lamanno]
[2022-01-13 22:53:44,342]   DEBUG [count_lamanno] [index] k-mer length: 31
[2022-01-13 22:53:44,347]   DEBUG [count_lamanno] [index] number of targets: 1,514,070
[2022-01-13 22:53:44,347]   DEBUG [count_lamanno] [index] number of k-mers: 1,567,912,597
[2022-01-13 22:53:44,347]   DEBUG [count_lamanno] [index] number of equivalence classes: 13,127,359
[2022-01-13 22:53:44,389]   ERROR [count_lamanno]
[index] k-mer length: 31
[index] number of targets: 1,514,070
[index] number of k-mers: 1,567,912,597
[index] number of equivalence classes: 13,127,359
[2022-01-13 22:53:44,426]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/main.py", line 856, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/main.py", line 212, in parse_count
    count_velocity(
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/count.py", line 1510, in count_velocity
    bus_result = kallisto_bus(
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/validate.py", line 110, in inner
    results = func(*args, **kwargs)
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/count.py", line 147, in kallisto_bus
    run_executable(command)
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/dry/__init__.py", line 24, in inner
    return func(*args, **kwargs)
  File "/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/utils.py", line 195, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/Users/Simoni/opt/anaconda3/envs/kb/lib/python3.8/site-packages/kb_python/bins/darwin/kallisto/kallisto bus -i /Users/Simoni/Desktop/scRNA/CD45/DIY_method/hs_cDNA_introns.idx -o . -x 10XV3 Endo_63_S1_L001_I2_001.fastq.gz Endo_63_S1_L002_R2_001.fastq.gz Endo_63_S1_L002_I1_001.fastq.gz Endo_63_S1_L002_I2_001.fastq.gz Endo_63_S1_L001_R1_001.fastq.gz Endo_63_S1_L001_I1_001.fastq.gz Endo_63_S1_L002_R1_001.fastq.gz Endo_63_S1_L001_R2_001.fastq.gz' died with <Signals.SIGKILL: 9>.
[2022-01-13 22:53:44,694]   DEBUG [main] Removing `./tmp` directory
```
Any thoughts? Thank you!

**Comment by Lioscro** [comment]
Hi, @SimoniMD,
The Illumina index files shouldn't be provided as inputs. Specifically, you can just remove the FASTQ files with `I1` and `I2` in the file name.

Additionally, I notice the overall ordering of FASTQs seem incorrect based on their file names. Try instead,
```
kb count \
Endo_63_S1_L001_R1_001.fastq.gz \
Endo_63_S1_L001_R2_001.fastq.gz \
Endo_63_S1_L002_R1_001.fastq.gz \
Endo_63_S1_L002_R2_001.fastq.gz \
...
```

**Comment by SimoniMD** [comment]
Thanks, some follow-up questions:

Didn't realize i didn't need the index files. If I included the index files in my initial analysis as well, would that change the kb output? I also didn't pay attention to the order of the files - does that matter? I've already done analysis and this is not something I paid attention to, so just wondering if I have to go back and repeat everything.

This was the base of my initial analysis code:
`kb count \
file1.fastq.gz file2.fastq.gz \
-i Homo_sapiens.GRCh38.cdna.all.index \
-x 10XV3 \
-g t2g.txt \
-t 8 \
--cellranger`

where "file1", "file2", etc. were just all my fastqs.

**Comment by Lioscro** [comment]
Yes, the first of each pair is considered to contain the cell barcodes and UMIs, and the second is considered to contain the cDNA reads. For instance, the first read in R1 is inseparable with the first read in R2 because R1 tells you which cell and mRNA molecule the R2 read arose from.

Therefore, mixing up the order will lead to nonsense results, either by the fact that kallisto will try an align the cell barcode and UMI sequences to genes, or due to considering parts of cDNA as the cell barcode and UMI sequences.

I strongly urge you to go back to the commands you ran previously to verify you provided the FASTQs in the proper order.

**Comment by SimoniMD** [comment]
Thanks, will do.

In case I have to repeat the kb commands, and to relate this to the original question...if I obtain both the spliced/unspliced matrcies, can I use the outputs to do the typical Seurat analysis? or the matrix outputs would be completely different and I would still need to do both the --cellranger and the --lamanno workflows to get the RNA velocity matrix as well the regular count matrix for Seurat?
