### ISSUE TITLE
kb_python.validate.ValidateError: ABCDE/merged.bus has no BUS records

### ISSUE THREAD

**Issue by stupidstupidstupidstupid** [pachterlab/kb_python#163]
Hi!

I met an error when trying to run kb count

!kb count --h5ad -i index.idx_cdna,index.idx_intron.0,index.idx_intron.1,index.idx_intron.2 -g t2g.txt -x 10xv3 -o ABCDE \
-c1 cdna_t2c.txt -c2 intron_t2c.txt --workflow lamanno --filter bustools -t 2 --overwrite\
Pc3_shNC_FRAS220073724-1r_1.clean.fq.gz\
Pc3_shNC_FRAS220073724-1r_2.clean.fq.gz

[2022-05-18 02:44:31,144] WARNING [main] Support for split indices will be deprecated in the next major release. Please read the release notes on GitHub for more information. 
[2022-05-18 02:44:33,308]    INFO [count_lamanno] Generating BUS file using 4 indices
[2022-05-18 02:44:33,309]    INFO [count_lamanno] Using index index.idx_cdna to generate BUS file to ABCDE/tmp/bus_part0 from
[2022-05-18 02:44:33,310]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_1.clean.fq.gz
[2022-05-18 02:44:33,310]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_2.clean.fq.gz
[2022-05-18 03:02:48,612]    INFO [count_lamanno] Sorting BUS file ABCDE/tmp/bus_part0/output.bus to /home/pol/PycharmProjects/pythonProject/ABCDE/tmp/tmpb0d4rrfa
[2022-05-18 03:02:54,338]    INFO [count_lamanno] Using index index.idx_intron.0 to generate BUS file to ABCDE/tmp/bus_part1 from
[2022-05-18 03:02:54,338]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_1.clean.fq.gz
[2022-05-18 03:02:54,338]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_2.clean.fq.gz
[2022-05-18 03:19:50,889]    INFO [count_lamanno] Sorting BUS file ABCDE/tmp/bus_part1/output.bus to /home/pol/PycharmProjects/pythonProject/ABCDE/tmp/tmphrncar59
[2022-05-18 03:19:55,778]    INFO [count_lamanno] Using index index.idx_intron.1 to generate BUS file to ABCDE/tmp/bus_part2 from
[2022-05-18 03:19:55,779]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_1.clean.fq.gz
[2022-05-18 03:19:55,779]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_2.clean.fq.gz
[2022-05-18 03:34:54,990]    INFO [count_lamanno] Sorting BUS file ABCDE/tmp/bus_part2/output.bus to /home/pol/PycharmProjects/pythonProject/ABCDE/tmp/tmpkt_o2et3
[2022-05-18 03:34:59,969]    INFO [count_lamanno] Using index index.idx_intron.2 to generate BUS file to ABCDE/tmp/bus_part3 from
[2022-05-18 03:34:59,969]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_1.clean.fq.gz
[2022-05-18 03:34:59,969]    INFO [count_lamanno]         Pc3_shNC_FRAS220073724-1r_2.clean.fq.gz
[2022-05-18 03:51:19,857]    INFO [count_lamanno] Sorting BUS file ABCDE/tmp/bus_part3/output.bus to /home/pol/PycharmProjects/pythonProject/ABCDE/tmp/tmpth0gytzx
[2022-05-18 03:51:24,925]    INFO [count_lamanno] Mashing BUS records to ABCDE from
[2022-05-18 03:51:24,925]    INFO [count_lamanno]         ABCDE/tmp/bus_part0
[2022-05-18 03:51:24,925]    INFO [count_lamanno]         ABCDE/tmp/bus_part1
[2022-05-18 03:51:24,925]    INFO [count_lamanno]         ABCDE/tmp/bus_part2
[2022-05-18 03:51:24,925]    INFO [count_lamanno]         ABCDE/tmp/bus_part3
[2022-05-18 03:52:27,004]    INFO [count_lamanno] Sorting BUS file ABCDE/mashed.bus to /home/pol/PycharmProjects/pythonProject/ABCDE/tmp/tmpwrzhndd_
[2022-05-18 03:52:33,528]    INFO [count_lamanno] Merging BUS records in ABCDE/mashed.bus to ABCDE
[2022-05-18 03:53:21,235]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/main.py", line 1301, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/main.py", line 482, in parse_count
    count_velocity(
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/count.py", line 1897, in count_velocity
    bus_result = kallisto_bus_split(
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/count.py", line 269, in kallisto_bus_split
    merge_result = bustools_merge(
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/validate.py", line 121, in inner
    validate(path)
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/validate.py", line 88, in validate
    VALIDATORS[ext](path)
  File "/home/pol/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/kb_python/validate.py", line 40, in validate_bus
    raise ValidateError(f'{path} has no BUS records')
kb_python.validate.ValidateError: ABCDE/merged.bus has no BUS records

What should I do to fix it?

**Comment by Yenaled** [comment]
Try it without using multiple index files.

**Comment by Lioscro** [comment]
Hi, @stupidstupidstupidstupid,
As @Yenaled suggested, using split indices (by providing `-n` in the `kb index` step and a comma-delimited list to the `-i` option in the `kb count` step) results in loss of reads. This is probably why one of your BUS files have no records (all the reads have been lost).

We are in the process of deprecating this functionality and, in the meantime, recommend using a full index instead. You may wish to use `--include-attributes` option during the `kb index` step to include only GTF entries that you are interested, similar to how Cellranger filters their GTF (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/references).
