### ISSUE TITLE
error when running kb count -tcc

### ISSUE THREAD

**Issue by karthikj89** [pachterlab/kb_python#199]
I am finding an error when I am trying to run the kb count command with the -tcc option to count isoform expression from SMARTSEQ2 data. I am running the command with data from 15 samples in the batch.txt file but the resulting cells_x_tcc.mtx only has 12 rows. This may be causing an error when it starts to generate the files in the quant_unfiltered folder?

The error message I see is: 
```
Fragment length distribution file contains 15 valid lines; expected: 12
```

This is the exact command that was run
```
kb count --tcc -t 4 -i cdna.all.idx -g t2g.txt -o /path/to/output -x SMARTSEQ2 --parity paired --strand unstranded /path/to/batch.txt
```

The output error message is as follows

```
[2023-03-25 05:38:17,997]    INFO [count] Using index /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/tmp/Homo_sapiens.GRCh38.cdna.all.idx to generate BUS file to /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea from
[2023-03-25 05:38:17,998]    INFO [count]         /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/tmp/tmpbzs3fk38
[2023-03-25 05:41:34,655]    INFO [count] Sorting BUS file /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/output.bus to /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/tmp/output.s.bus
[2023-03-25 05:41:39,978]    INFO [count] Inspecting BUS file /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/tmp/output.s.bus
[2023-03-25 05:41:41,087]    INFO [count] Generating count matrix /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/counts_unfiltered/cells_x_tcc from BUS file /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/tmp/output.s.bus
[2023-03-25 05:41:46,692]    INFO [count] Quantifying transcript abundances to /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/quant_unfiltered from mtx file /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/counts_unfiltered/cells_x_tcc.mtx
[2023-03-25 05:41:52,209]   ERROR [count] 
[index] k-mer length: 31
[index] number of targets: 252,798
[index] number of k-mers: 0
[index] number of equivalence classes: 1,134,070
[index] number of equivalence classes loaded from file: 1,134,070
[tcc] Parsing transcript-compatibility counts (TCC) file as a matrix file
[tcc] Matrix dimensions: 12 x 1,134,070
Error: Fragment length distribution file contains 15 valid lines; expected: 12
[2023-03-25 05:41:52,209]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kb_python/main.py", line 1305, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/usr/local/lib/python3.9/site-packages/kb_python/main.py", line 550, in parse_count
    count(
  File "/usr/local/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kb_python/count.py", line 1151, in count
    quant_result = kallisto_quant_tcc(
  File "/usr/local/lib/python3.9/site-packages/kb_python/validate.py", line 116, in inner
    results = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kb_python/count.py", line 202, in kallisto_quant_tcc
    run_executable(command)
  File "/usr/local/lib/python3.9/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/usr/local/lib/python3.9/site-packages/kb_python/bins/linux/kallisto/kallisto quant-tcc -o /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/quant_unfiltered -i /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/index.saved -e /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/matrix.ec -g /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/tmp/Homo_sapiens.GRCh38.t2g.txt -t 4 -f /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/flens.txt /usr/app/src/scratch/dacde551-e9e2-4413-9acb-add0f8acf2a7_1/job.0.Trachea/counts_unfiltered/cells_x_tcc.mtx' returned non-zero exit status 1.

```

**Comment by Yenaled** [comment]
How did you generate your index file? It says number of k-mers: 0 which suggest something might be wrong with the index.

What's the mapping rate? Are there files where zero reads are getting mapped?

**Comment by karthikj89** [comment]
Thanks for your quick reply! 

I was able to resolve the issue by removing the fastq files with size < 1000 bytes from the batch.txt file. It looks like those files have too few reads. Does this sound reasonable?

**Comment by Yenaled** [comment]
Ooh yes, that sounds reasonable -- with such few reads, nothing will be mapped and those samples won't be included in the final matrix.
