### ISSUE TITLE
Signals.SIGILL: 4 when running kb ref

### ISSUE THREAD

**Issue by yquint21** [pachterlab/kb_python#222]
**Describe the issue**
Hi, I'm unable to create a Kallisto index. When running the kb ref command (python 3.10.13 and kb 0.27.3) all files files are generated with the exception of the index file. When it starts creating the index file it gives an error and returns a SIGILL: 4 signal. I'm not sure if I'm doing something wrong. Any help would be greatly appreciated. 

**What is the exact command that was run?**
```
kb ref "/genomes/hg38/hg38.fa" "/genomes/hg38/hg38.annotation.gtf" -i hg38.idx -g hg38_t2g.txt -f1 hg38_cdna.fa -f2 hg38_intron.fa -c1 hg38_cdna_t2c.txt -c2 hg38_intron_t2c.txt --workflow lamanno --verbose
```

**Command output (with `--verbose` flag)**
```
[2023-10-30 09:59:58,624]   DEBUG [main] Printing verbose output
[2023-10-30 10:00:00,830]   DEBUG [main] kallisto binary located at /vol/mbconda/yquint/kb_python/bin/kallisto
[2023-10-30 10:00:00,830]   DEBUG [main] bustools binary located at /vol/mbconda/yquint/kb_python/bin/bustools
[2023-10-30 10:00:00,830]   DEBUG [main] Creating `tmp` directory
[2023-10-30 10:00:01,136]   DEBUG [main] Namespace(list=False, command='ref', tmp=None, keep_tmp=False, verbose=True, i='hg38.idx', g='hg38_t2g.txt', f1='hg38_cdna.fa', include_attribute=None, exclude_attribute=None, f2='hg38_intron.fa', c1='hg38_cdna_t2c.txt', c2='hg38_intron_t2c.txt', d=None, k=None, workflow='lamanno', overwrite=False, kallisto='kallisto', bustools='bustools', fasta='/home/yquint/genomes/hg38/hg38.fa', gtf='/home/yquint/genomes/hg38/hg38.annotation.gtf', feature=None, no_mismatches=False, flank=None)
[2023-10-30 10:00:01,136]    INFO [ref_lamanno] Preparing /home/yquint/genomes/hg38/hg38.fa, /home/yquint/genomes/hg38/hg38.annotation.gtf
[2023-10-30 10:01:07,613]    INFO [ref_lamanno] Splitting genome /home/yquint/genomes/hg38/hg38.fa into cDNA at /home/yquint/test_KB_index/tmp/tmp_a9aq2i6
[2023-10-30 10:02:17,598]    INFO [ref_lamanno] Creating cDNA transcripts-to-capture at /home/yquint/test_KB_index/tmp/tmpw0m8i3r3
[2023-10-30 10:02:19,201]    INFO [ref_lamanno] Splitting genome into introns at /home/yquint/test_KB_index/tmp/tmpbqw0q731
[2023-10-30 10:09:36,057]    INFO [ref_lamanno] Creating intron transcripts-to-capture at /home/yquint/test_KB_index/tmp/tmp9safbpe0
[2023-10-30 10:09:48,726]    INFO [ref_lamanno] Concatenating 1 cDNA FASTAs to hg38_cdna.fa
[2023-10-30 10:10:08,485]    INFO [ref_lamanno] Concatenating 1 cDNA transcripts-to-captures to hg38_cdna_t2c.txt
[2023-10-30 10:10:12,186]    INFO [ref_lamanno] Concatenating 1 intron FASTAs to hg38_intron.fa
[2023-10-30 10:10:45,153]    INFO [ref_lamanno] Concatenating 1 intron transcripts-to-captures to hg38_intron_t2c.txt
[2023-10-30 10:10:52,284]    INFO [ref_lamanno] Concatenating cDNA and intron FASTAs to /home/yquint/test_KB_index/tmp/tmpmu1gex2r
[2023-10-30 10:11:27,343]    INFO [ref_lamanno] Creating transcript-to-gene mapping at hg38_t2g.txt
[2023-10-30 10:11:54,122]    INFO [ref_lamanno] Indexing /home/yquint/test_KB_index/tmp/tmpmu1gex2r to hg38.idx
[2023-10-30 10:11:54,122]   DEBUG [ref_lamanno] kallisto index -i hg38.idx -k 31 /home/yquint/test_KB_index/tmp/tmpmu1gex2r
[2023-10-30 10:11:55,225]   DEBUG [ref_lamanno]
[2023-10-30 10:11:55,225]   ERROR [ref_lamanno]
[2023-10-30 10:11:55,225]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/kb_python/main.py", line 1305, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/kb_python/main.py", line 249, in parse_ref
    ref_lamanno(
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/kb_python/ref.py", line 746, in ref_lamanno
    index_result = kallisto_index(combined_path, index_path, k=k or 31)
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/kb_python/ref.py", line 239, in kallisto_index
    run_executable(command)
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "/vol/mbconda/yquint/kb_python/lib/python3.10/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/vol/mbconda/yquint/kb_python/bin/kallisto index -i hg38.idx -k 31 /home/yquint/test_KB_index/tmp/tmpmu1gex2r' died with <Signals.SIGILL: 4>.
[2023-10-30 10:11:55,939]   DEBUG [main] Removing `tmp` directory

```

**Comment by Yenaled** [comment]
You probably ran out of memory. Run it on a machine that has over 64 gb of memory.

**Comment by yquint21** [comment]
Thank you for your response. The server I'm using has well over 64 gb of memory, so that should not be the problem.

**Comment by Yenaled** [comment]
There are a couple of possibilities I can think of:
- Your .fa file is corrupted
- Your machine is not compatible with the packaged kallisto binary. You may need to install kallisto from source (aka generate a new kallisto binary) and then run kb ref --kallisto=/path/to/new/kallisto ...

**Comment by yquint21** [comment]
Installing the Kallisto from source fixed the problem. Thank you!!

**Comment by ChrisChr1** [comment]
I ran `kb ref --overwrite -d human -i dindex.idx -g t2gd.txt` to get the index and t2g.txt file. I am also getting a similar signals error after running kb count. 

`kb count -i dindex.idx -g t2gd.txt -o kbcount_d -x 10xv3 --strand unstranded -t 16 VP4_SubLib1_RD_ATCC_S1_R1_001.fastq.gz VP4_SubLib1_RD_ATCC_S1_R2_001.fastq.gz`

```
2023-12-27 10:05:12,145]    INFO [count] Using index dindex.idx to generate BUS file to kbcount_d from
[2023-12-27 10:05:12,146]    INFO [count]         VP4_SubLib1_RD_ATCC_S1_R1_001.fastq.gz
[2023-12-27 10:05:12,146]    INFO [count]         VP4_SubLib1_RD_ATCC_S1_R2_001.fastq.gz
[2023-12-27 10:05:13,365]   ERROR [count] 
[2023-12-27 10:05:13,366]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "lib/python3.7/site-packages/kb_python/main.py", line 1618, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/nethome/mariskanishca/.local/lib/python3.7/site-packages/kb_python/main.py", line 746, in parse_count
    store_num=args.num
  File "lib/python3.7/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "lib/python3.7/site-packages/kb_python/count.py", line 1293, in count
    n=store_num
  File "lib/python3.7/site-packages/kb_python/count.py", line 203, in kallisto_bus
    run_executable(command)
  File "lib/python3.7/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "lib/python3.7/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command 'lib/python3.7/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i dindex.idx -o kbcount_d -x 10xv3 -t 16 --unstranded VP4_SubLib1_RD_ATCC_S1_R1_001.fastq.gz VP4_SubLib1_RD_ATCC_S1_R2_001.fastq.gz' died with <Signals.SIGILL: 4>.
```

I also don't suspect that there is a lack of memory. Thank you in advance for your help.

**Comment by Yenaled** [comment]
The solution is already posted above

**Comment by ChrisChr1** [comment]
I apologize I am new to this. You are referring to this code below?
```
git clone https://github.com/pachterlab/kallisto
cd kallisto
mkdir build
cd build
cmake ..
make
make install
```
