### ISSUE TITLE
0 reads pseudoaligned

### ISSUE THREAD

**Issue by matasV99** [pachterlab/kb_python#278]
Dear developers,

Thank you for developing such a great tool! I am using the kb-python pipeline to quantify transcripts in my single-cell RNAseq experiments. The pipeline works for all but one sample. and I get an error that 0 reads are pseudoaligned. I don't have access to BCL files so I can't regenerate the .fastq.gz files. This sample gets aligned perfectly using _CellRanger count_ command, so I wanted to ask developers if this sample can be salvaged, perhaps, by changing the default .fastq header parameters for _kb count_. Alternatively, I am looking for some advice on why my .fastq file might look so different from my other samples [see below].

**What is the exact command that was run?**
kb ref \
-i /mnt/sdd/output/hg38_cDNA_introns.idx \
-g /mnt/sdd/output/t2g.txt \
-f1 /mnt/sdd/output/cDNA.fa \
-f2 /mnt/sdd/output/introns.fa \
-c1 /mnt/sdd/output/cDNA_tx_to_capture.txt \
-c2 /mnt/sdd/output/introns_tx_to_capture.txt \
--workflow lamanno \
/mnt/sdd/refdata-gex-GRCh38-2020-A/fasta/genome.fa \
/mnt/sdd/refdata-gex-GRCh38-2020-A/genes/genes.gtf"

nohup kb count \ -i /mnt/sdd/output/hg38_cDNA_introns.idx \ 
-g  /mnt/sdd/output/t2g.txt \
 -x 10xv3 \ 
-o kb_output \ 
-t 16 \ 
-m 100G \ 
--verbose \ 
-c1  /mnt/sdd/output/cDNA_tx_to_capture.txt \
 -c2  /mnt/sdd/output/introns_tx_to_capture.txt \ 
--workflow lamanno \
 /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_001.fastq.gz \ /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_001.fastq.gz >  /mnt/sdd/output/MLO0_kb_count_log.out &

**Command output (with `--verbose` flag)**
[2024-12-09 15:28:07,107]   DEBUG [main] Printing verbose output
[2024-12-09 15:28:09,310]   DEBUG [main] kallisto binary located at /home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/bins/linux/kallisto/kallisto
[2024-12-09 15:28:09,310]   DEBUG [main] bustools binary located at /home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/bins/linux/bustools/bustools
[2024-12-09 15:28:09,310]   DEBUG [main] Creating `kb_output/tmp` directory
[2024-12-09 15:28:09,310]   DEBUG [main] Namespace(list=False, command='count', tmp=None, keep_tmp=False, verbose=True, i='/mnt/sdd/output/hg38_cDNA_introns.idx', g='/mnt/sdd/output/t2g.txt', x='10xv3', o='kb_output', num=False, w=None, r=None, t=16, m='100G', strand=None, inleaved=False, genomebam=False, aa=False, gtf=None, chromosomes=None, workflow='lamanno', em=False, mm=False, tcc=False, filter=None, filter_threshold=None, c1='/mnt/sdd/output/cDNA_tx_to_capture.txt', c2='/mnt/sdd/output/introns_tx_to_capture.txt', overwrite=False, dry_run=False, batch_barcodes=False, loom=False, h5ad=False, loom_names='barcode,target_name', sum='none', cellranger=False, gene_names=False, N=None, report=False, no_inspect=False, long=False, threshold=0.8, error_rate=None, platform='ONT', kallisto='/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/bins/linux/kallisto/kallisto', bustools='/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/bins/linux/bustools/bustools', opt_off=False, k=31, no_validate=False, no_fragment=False, union=False, no_jump=False, quant_umis=False, keep_flags=False, parity=None, fragment_l=None, fragment_s=None, bootstraps=None, matrix_to_files=False, matrix_to_directories=False, fastqs=['/mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_002.fastq.gz', '/mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_002.fastq.gz'])
[2024-12-09 15:28:11,981]    INFO [count_lamanno] Using index /mnt/sdd/output/hg38_cDNA_introns.idx to generate BUS file to kb_output from
[2024-12-09 15:28:11,981]    INFO [count_lamanno]         /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_002.fastq.gz
[2024-12-09 15:28:11,981]    INFO [count_lamanno]         /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_002.fastq.gz
[2024-12-09 15:28:11,981]   DEBUG [count_lamanno] kallisto bus -i /mnt/sdd/output/hg38_cDNA_introns.idx -o kb_output -x 10xv3 -t 16 /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_002.fastq.gz /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_002.fastq.gz
[2024-12-09 15:28:12,082]   DEBUG [count_lamanno] 
[2024-12-09 15:28:12,082]   DEBUG [count_lamanno] [bus] Note: Strand option was not specified; setting it to --fr-stranded for specified technology
[2024-12-09 15:29:37,560]   DEBUG [count_lamanno] [index] k-mer length: 31
[2024-12-09 15:30:40,429]   DEBUG [count_lamanno] [index] number of targets: 1,221,221
[2024-12-09 15:30:40,530]   DEBUG [count_lamanno] [index] number of k-mers: 1,520,719,025
[2024-12-09 15:30:40,630]   DEBUG [count_lamanno] [quant] running in paired-end mode
[2024-12-09 15:30:40,630]   DEBUG [count_lamanno] [quant] will process sample 1: /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_002.fastq.gz
[2024-12-09 15:30:40,630]   DEBUG [count_lamanno] /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_002.fastq.gz
[2024-12-09 15:30:42,332]   DEBUG [count_lamanno] [quant] finding pseudoalignments for the reads ...
[2024-12-09 15:30:44,134]   DEBUG [count_lamanno] [progress] 1M reads processed (0.0% mapped)
[2024-12-09 15:30:45,836]   DEBUG [count_lamanno] [progress] 2M reads processed (0.0% mapped)
<...>
[2024-12-09 15:39:52,826]   DEBUG [count_lamanno] [progress] 336M reads processed (0.0% mapped)
[2024-12-09 15:39:52,826]   DEBUG [count_lamanno] [progress] 337M reads processed (0.0% mapped)              done
[2024-12-09 15:39:52,826]   DEBUG [count_lamanno] [quant] processed 337,690,985 reads, 0 reads pseudoaligned
[2024-12-09 15:39:52,827]   DEBUG [count_lamanno] [~warn] no reads pseudoaligned.
[2024-12-09 15:39:53,227]   DEBUG [count_lamanno] 
[2024-12-09 15:39:56,730]   ERROR [count_lamanno] 
[bus] Note: Strand option was not specified; setting it to --fr-stranded for specified technology
[index] k-mer length: 31
[index] number of targets: 1,221,221
[index] number of k-mers: 1,520,719,025
[quant] running in paired-end mode
[quant] will process sample 1: /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_002.fastq.gz
/mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_002.fastq.gz
[quant] finding pseudoalignments for the reads ...
[progress] 1M reads processed (0.0% mapped)
[progress] 2M reads processed (0.0% mapped)
<...>
[progress] 337M reads processed (0.0% mapped)              done
[quant] processed 337,690,985 reads, 0 reads pseudoaligned
[~warn] no reads pseudoaligned.

[2024-12-09 15:39:56,730]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/main.py", line 1926, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/main.py", line 676, in parse_count
    count_velocity(
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/count.py", line 2480, in count_velocity
    bus_result = kallisto_bus(
                 ^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/count.py", line 223, in kallisto_bus
    run_executable(command)
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/ubuntu/miniconda3/lib/python3.12/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i /mnt/sdd/output/hg38_cDNA_introns.idx -o kb_output -x 10xv3 -t 16 /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R1_002.fastq.gz /mnt/sdd/XHO006_MLO0/XHO006_HS006-PE-R00456_S1_L006_R2_002.fastq.gz' returned non-zero exit status 1.
[2024-12-09 15:39:56,734]   DEBUG [main] Removing `kb_output/tmp` directory

Attaching the .fastq file snapshots for your reference as I think it is at the root of this problem. This is a sample that works: 
![image](https://github.com/user-attachments/assets/600352b4-276d-44b1-b657-dc2d886c02d6)
This is a sample that does not work: 
![image](https://github.com/user-attachments/assets/e83e15ce-9a7f-4218-b683-08af19e7b76d)

**Comment by Yenaled** [comment]
Hmm, I’m not sure what’s going on.

Can you try running kb count with the option: --strand=reverse

Maybe whatever technology produced those FASTQ files had a different stranded library prep.

**Comment by Yenaled** [comment]
Can you email me a few thousand sequences from your FASTQ files? I’ll take a look. (Email is in my GitHub profile)

**Comment by matasV99** [comment]
Sent you an email!

**Comment by Yenaled** [comment]
What samples are these?  I'm also getting 0% mapping, so I BLASTed a few sequences and it seems that everything is originating from a ribosomal or intergenic region. 

Those reads will not be mapped by kallisto since they're not part of the transcriptome (they will get aligned by CellRanger because although CellRanger only quantifies the transcriptome, it will do alignment to the entire genome.).

**Comment by matasV99** [comment]
These are midbrain organoid samples. I also blasted some of the sequences and they align to protein-coding regions of hg38. For example this read: "NCCAACGCACAAATCCCGTTATAATG", maps well: 
![image](https://github.com/user-attachments/assets/f884dd11-90a1-4f54-a52b-c79da2950891)

Thus, it seems that it is not all ribosomal and intergenic region reads. Do you have any other suggestions for troubleshooting?

**Comment by Yenaled** [comment]
That sequence is only 26 bp, kallisto’s k-mer size is 31.

I cannot find any read that aligns uniquely within exonic or intronic regions.

If you think you can find one, feel free to copy and paste and I’ll show you why kallisto does not align it.

**Comment by matasV99** [comment]
Okay, for example, this: NTGCCTGTAATGGGAAGGAGATGTCACCAACCAGGCAACTCCGGAGGTGCCCTGGAAGTCATTGCCTGACAATAACTGATGTTCCCGTCACTGTTTAT

This comes up as a protein-coding gene: FAM229B 
![image](https://github.com/user-attachments/assets/2532d7b5-7b21-4134-8d59-af68b2d52903)

Why would Kallisto not align this?

On the other hand, it is strange that my R2 .fastq.gz file has reads of length 99bp, while R1 .fastq.gz file has reads of length 26 bp... Have you ever seen that? I also checked my I1 .fastq.gz file and I did not mix up or rename my index file and R1 file...

**Comment by Yenaled** [comment]
Sorry, I was being a total idiot -- now that you mention about R1 lengths being 26, the issue is that you're using 10xv3 (which means the R1 should be 28 bp's). It's likely that the FASTQ files you have are produced by 10xv2, not 10xv3.

If you use -x 10xv2, it should work.

**Comment by matasV99** [comment]
It works! I can't thank you enough! 

Matas

**Comment by matasV99** [comment]
Hi @Yenaled,

Upon further inspection, I realized that these exact same FASTQ files get assigned Chromium v3 chemistry in the CellRanger pipeline, even though the base pair length is 26: 
![image](https://github.com/user-attachments/assets/2c86b84f-e01c-4ee0-bde1-a52d1b7ebbd7)

For chemistry detection, the  Cellranger pipeline makes use of the first 16bases from the input Read 1 FASTQ file and maps it against a set of 10x whitelists. After sampling 100k reads from Read 1 FASTQ file, 94.4% of valid barcodes were mapped against the v3 whitelist.

I contacted 10X genomics tech help to inquire about this, and they outlined that 28 base pair reads for v3 is a recommendation, not a necessary prerequisite for a read to be chromium v3 chemistry. Their point is that you simply get UMI collision (reduced assay sensitivity) if you use 26 bp reads for v3 chemistry, but people have used shorter reads than 28 for v3 chemistry in their experience.

My question for you is: 
a) Does _kallisto bus_ choose between v2 chemistry vs v3 chemistry solely based on base pair length in R1  file or does it also align it against whitelist barcodes from 10x?
b) Is there any quick-fix I could do to align my 26bp R1 FASTQ sample using v3 chromium chemistry?

**Comment by Yenaled** [comment]
@matasV99 Happy New Year!  v2 and v3 both have 16 bp barcodes at the start of read 1. The only difference is that v3 has longer UMIs (making the total read length 28 bp rather than 26 bp).

kallisto chooses v2 chemistry if you supply -x 10xv2 and chooses v3 chemistry is you supply -x 10xv3 in your command. The initial processing of sequencing reads is mostly the same (the main difference is that kallisto will extract the longer UMIs if you supply -x 10xv3; but -x 10xv2 will also work -- you just won't extract the full 12-bp UMI sequence). Afterwards, the workflow performs correction to the "whitelist". The whitelist chosen depends on whether you supplied -x 10xv2 or -x 10xv3, and they are different (the v2 whitelist has around 700K sequences while v3 whitelist has around 6M sequences).

If you want to align 26bp R1 using the v3 whitelist, you can download the v3 whitelist (e.g. https://github.com/Lioscro/ngs-tools/blob/main/ngs_tools/chemistry/whitelists/10x_version3_whitelist.txt.gz ), unzip it, and supply the filename to the -w option when running kb count -x 10xv2. This effectively means: Run 10xv2 (i.e. 16-bp barcode + 10-bp UMIs) but use the v3 whitelist. If you want to use the v2 whitelist, you can download it here: https://github.com/Lioscro/ngs-tools/blob/main/ngs_tools/chemistry/whitelists/10x_version3_whitelist.txt.gz 

(In other words, by default, a whitelist is chosen for you but you can override it by using the -w option).

kb-python/kallisto is a very flexible tool; you can choose where and how long the barcodes+UMIs are that you want to extract and what whitelist you want to use. You can customize it however you like. If you want to do something: like 13 bp barcodes at the start of read 1 and 11 bp barcodes at the start of read 2 and use a random whitelist you find online, well, kb-python can also handle that if you configure the options accordingly :)

**Comment by matasV99** [comment]
@Yenaled That did the trick! Now, instead of getting spliced/unspliced matrix for 30 filtered cells, I recover 1751 from this sample! Thank you for your informative and rapid responses.
