### ISSUE TITLE
kb count with 10Xv4

### ISSUE THREAD

**Issue by carlacohen** [pachterlab/kb_python#280]
Hi there, I have been using kb count successfully to analyse single cell transcriptomics data generated with 10Xv3 technology. However I am having trouble performing the analysis now that my lab mates have updated to performing experiments with 10Xv4. I believe this is unsupported in kb_python 0.27.3. 

I am working on a computing cluster and submitting the following command using a slurm queue. I have already built the index successfully. 

Command: 
```
kb count -i geneset.dir/index.idx -w 3M-3pgex-may-2023.txt.gz -g geneset.dir/t2g.txt \
  -c1 geneset.dir/cdna_t2c.txt -c2 geneset.dir/intron_t2c.txt -x 0,0,16:0,16,28:1,0,0   \
  -o kallisto.dir/MSK1516-SYN-HIP-OA-test/bus --workflow nucleus \
  --loom  data.dir/MSK1516-SYN-HIP-OA-test.fastq.1.gz data.dir/MSK1516-SYN-HIP-OA-test.fastq.2.gz  \
  2> kallisto.dir/MSK1516-SYN-HIP-OA-test/bus_kblog.log
```
As you can see I am including the -w flag to specify the barcode whitelist, and the -x flag to specify the barcode/UMI positions. 

The job runs and I don't run out of RAM, but the count matrix is not generated. From the slurm log file I can see I need about 70GB RAM and I am allocating 200GB. 

This is the output of the bus_kblog.log file

```
[2024-12-18 11:55:10,487]    INFO [count_lamanno] Using index geneset.dir/index.idx to generate BUS file to kallisto.dir/MSK1250-SYN-KNEE-H-test/bus from
[2024-12-18 11:55:10,487]    INFO [count_lamanno]         data.dir/MSK1250-SYN-KNEE-H-test.fastq.1.gz
[2024-12-18 11:55:10,487]    INFO [count_lamanno]         data.dir/MSK1250-SYN-KNEE-H-test.fastq.2.gz
[2024-12-18 12:02:58,709]    INFO [count_lamanno] Sorting BUS file kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/output.bus to kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/tmp/output.s.bus
[2024-12-18 12:03:03,617]    INFO [count_lamanno] Inspecting BUS file kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/tmp/output.s.bus
[2024-12-18 12:03:04,830]    INFO [count_lamanno] Correcting BUS records in kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/tmp/output.s.bus to kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/tmp/output.s.c.bus with whitelist 3M-3pgex-may-2023.txt.gz
[2024-12-18 12:03:06,043]   ERROR [count_lamanno] Found 22031 barcodes in the whitelist
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
[2024-12-18 12:03:06,043]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/main.py", line 1305, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/main.py", line 491, in parse_count
    count_velocity(
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/count.py", line 1635, in count_velocity
    prev_result = bustools_correct(
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/validate.py", line 116, in inner
    results = func(*args, **kwargs)
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/count.py", line 330, in bustools_correct
    run_executable(command)
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/lib/python3.8/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/ceph/project/ancestryhca/ccohen/mamba_installation/conda/envs/scflow_kb/bin/bustools correct -o kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/tmp/output.s.c.bus -w 3M-3pgex-may-2023.txt.gz kallisto.dir/MSK1250-SYN-KNEE-H-test/bus/tmp/output.s.bus' died with <Signals.SIGABRT: 6>.
```

Please let me know if you are able to help decode this message, or if you have any other advice on using 10Xv4. 

Versions  
I am running this in a conda env with the following package versions: 
kb_python 0.27.3
kallisto: 0.48.0 (kallisto)
bustools: 0.42.0 (bustools)

**Comment by Yenaled** [comment]
Can you try unzipping the whitelist file.

and also, look and inspect the first few sequences in that file to make sure each line contains 16 nucleotide long sequences.

**Comment by carlacohen** [comment]
Thanks for the quick reply, this was indeed the issue!
