### ISSUE TITLE
Issue with sorting BUS files

### ISSUE THREAD

**Issue by Seandelao** [pachterlab/kb_python#31]
Hello, 

I am following the RNA velocity tutorial (https://www.kallistobus.tools/kb_velocity_tutorial.html); I have successfully built the Linnarsson index, but am running into an issue when generating the velocity matrices. When running the command: 

"! kb count -i index.idx -g transcripts_to_genes.txt -x 10xv3 -o output \
-c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt --lamanno \
/Users/seandelao/Desktop/85dpc_FASTQ_files/85dpc_1_S8_L001_R1_001.fastq.gz \
/Users/seandelao/Desktop/85dpc_FASTQ_files/85dpc_1_S8_L001_R2_001.fastq.gz \
/Users/seandelao/Desktop/85dpc_FASTQ_files/85dpc_1_S8_L002_R1_001.fastq.gz \
/Users/seandelao/Desktop/85dpc_FASTQ_files/85dpc_1_S8_L002_R2_001.fastq.gz

it runs through a few of the steps, but fails at sorting the BUS files. Here is the output and traceback: 

[2019-11-10 16:26:44,892]    INFO Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite.
[2019-11-10 16:26:44,892]    INFO Sorting BUS file output/output.bus to tmp/output.s.bus
[2019-11-10 16:27:39,756]    INFO Whitelist not provided
[2019-11-10 16:27:39,756]    INFO Copying pre-packaged 10XV3 whitelist to output
[2019-11-10 16:27:40,835]    INFO Inspecting BUS file tmp/output.s.bus
[2019-11-10 16:28:53,119]    INFO Correcting BUS records in tmp/output.s.bus to tmp/output.s.c.bus with whitelist output/10xv3_whitelist.txt
[2019-11-10 16:32:34,900]    INFO Sorting BUS file tmp/output.s.c.bus to output/output.unfiltered.bus
[2019-11-10 16:33:23,774]    INFO Capturing records from BUS file output/output.unfiltered.bus to tmp/spliced.bus with capture list cdna_transcripts_to_capture.txt
[2019-11-10 16:33:37,991]    INFO Sorting BUS file tmp/spliced.bus to output/spliced.unfiltered.bus
[2019-11-10 16:33:41,346]   ERROR An exception occurred
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/anaconda3/lib/python3.7/site-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
  File "/anaconda3/lib/python3.7/site-packages/kb_python/count.py", line 733, in count_velocity
    memory=memory
  File "/anaconda3/lib/python3.7/site-packages/kb_python/count.py", line 97, in bustools_sort
    run_executable(command)
  File "/anaconda3/lib/python3.7/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/anaconda3/lib/python3.7/site-packages/kb_python/bins/darwin/bustools/bustools sort -o output/spliced.unfiltered.bus -T tmp -t 8 -m 4G tmp/spliced.bus' died with <Signals.SIGSEGV: 11>.

Any idea what might be happening? Thanks!

**Comment by Lioscro** [comment]
Hi, @Seandelao!
I've experienced this problem when there are no BUS records in the file it is trying to sort.
To check whether the BUS file is empty,
1. Run `kb` with the `--keep-tmp` flag to prevent it from removing the temporary directory.
2. How large is the `tmp/spliced.bus` file? You can find out explicitly how many BUS records it has by running `bustools inspect tmp/spliced.bus` if you have `bustools` installed locally (not through kb).

**Comment by JoelPHoward** [comment]
Hi @Lioscro,
I am experiencing the same issue as @Seandelao.

When I run:
```
kb count --keep-tmp -i index.idx -g transcript_to_gene.txt -x 10xv2 -o output -t 4 -m 10G --lamanno --loom -c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt SRR8599150_S1_L001_R1_001.fastq.gz SRR8599150_S1_L001_R2_001.fastq.gz
```

I get the following output:
```
[2019-11-14 14:15:40,975]   INFO Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite.  
[2019-11-14 14:15:40,975]   INFO Sorting BUS file output/output.bus to tmp/output.s.bus
[2019-11-14 14:15:45,568]   ERROR An exception occurred
Traceback (most recent call last):
File "/Users/jsjoyal/.kb/lib/python3.7/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
File "/Users/jsjoyal/.kb/lib/python3.7/site-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
File "/Users/jsjoyal/.kb/lib/python3.7/site-packages/kb_python/count.py", line 689, in count_velocity
    memory=memory
File "/Users/jsjoyal/.kb/lib/python3.7/site-packages/kb_python/count.py", line 97, in bustools_sort
    run_executable(command)
File "/Users/jsjoyal/.kb/lib/python3.7/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/Users/jsjoyal/.kb/lib/python3.7/site-packages/kb_python/bins/darwin/bustools/bustools sort -o tmp/output.s.bus -T tmp -t 4 -m 10G output/output.bus' died with <Signals.SIGSEGV: 11>.
```
In the `tmp` dir, the only file present is `output.s.bus`, which is empty.

Any help would be appreciated.

**Comment by JoelPHoward** [comment]
Hi @Seandelao,

I recently ran into the same error, but realized that it was due to issues from building the index.
Specifically, when I ran `kb ref`:

The files `index.idx`, `transcripts_to_genes.txt`, `cdna_transcripts_to_capture.txt` and `intron_transcripts_to_capture.txt` were empty. If you type `ls -lth` in you output folder, you might see that these files are 0 bytes. 

I think the problem was with the reference fasta and gtf files that I was using. What worked for me was wget-ing the following reference files:
For human:

```
ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz
```

For mouse:
```
ftp://ftp.ensembl.org/pub/release-98/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
ftp://ftp.ensembl.org/pub/release-98/gtf/mus_musculus/Mus_musculus.GRCm38.98.gtf.gz
```

And once downloaded, remember to unzip them using `gunzip`.

Then running the following command to build the indexes might solve your problem:
```
kb ref -i index.idx -g transcripts_to_genes.txt -f1 cdna.fa -f2 intron.fa -c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt --lamanno Homo_sapiens.GRCh38.dna.primary_assembly.fa Homo_sapiens.GRCh38.98.gtf
```

Hope that helps!

**Comment by AminMahpour** [comment]
I am having the same issue when I use thread flags.

**Comment by Lioscro** [comment]
@AminMahpour Could you try running with the `--verbose` flag and post the output here?
