### ISSUE TITLE
kb unable to build index died with <Signals.SIGABRT: 6>

### ISSUE THREAD

**Issue by Gaura** [pachterlab/kb_python#42]
Hi,

I am trying to build velocity index using kb as shown here:https://www.kallistobus.tools/kb_velocity_index.html

This is my command and corresponding log:
kb ref -i index.idx -g transcripts_to_genes.txt -f1 cdna.fa -f2 intron.fa -c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt --lamanno GRCm38.primary_assembly.genome.fa gencode.vM23.annotation.gtf
[2019-11-12 15:19:24,787]    INFO Decompressing GRCm38.primary_assembly.genome.fa to tmp
[2019-11-12 15:19:24,787]    INFO Sorting GRCm38.primary_assembly.genome.fa
[2019-11-12 15:26:02,214]    INFO Decompressing gencode.vM23.annotation.gtf to tmp
[2019-11-12 15:26:02,215]    INFO Sorting gencode.vM23.annotation.gtf
[2019-11-12 15:26:50,436]    INFO Splitting genome into cDNA at cdna.fa
[2019-11-12 15:28:23,864]    INFO Creating cDNA transcripts-to-capture at cdna_transcripts_to_capture.txt
[2019-11-12 15:28:24,880]    INFO Splitting genome into introns at intron.fa
[2019-11-12 15:32:42,591]    INFO Creating intron transcripts-to-capture at cdna_transcripts_to_capture.txt
[2019-11-12 15:32:48,821]    INFO Concatenating cDNA and intron FASTAs
[2019-11-12 15:32:54,748]    INFO Creating transcript-to-gene mapping at transcripts_to_genes.txt
[2019-11-12 15:33:02,317]    INFO Indexing to index.idx
[2019-11-12 15:52:50,171]   ERROR An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/usr/local/lib/python3.7/site-packages/kb_python/main.py", line 100, in parse_ref
    overwrite=args.overwrite
  File "/usr/local/lib/python3.7/site-packages/kb_python/ref.py", line 373, in ref_lamanno
    index_result = kallisto_index(combined_path, index_path)
  File "/usr/local/lib/python3.7/site-packages/kb_python/ref.py", line 166, in kallisto_index
    run_executable(command)
  File "/usr/local/lib/python3.7/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/usr/local/lib/python3.7/site-packages/kb_python/bins/linux/kallisto/kallisto index -i index.idx -k 31 tmp/combined.fa' died with <Signals.SIGABRT: 6>.

I am not sure why does this error occur. I checked this https://unix.stackexchange.com/questions/529229/why-is-command-line-program-killed-by-sigabrt but that didn't help much.

Any suggesion on how to resolve it will be helpful.

Thanks,
Gaurav

**Comment by sbooeshaghi** [comment]
My intuition is that you ran out of RAM, as the standard velocity index is large. 

What are the specs of your machine that you ran `kb ref` on?

**Comment by Gaura** [comment]
Thanks, for your reply. I should have mentioned that I was monitoring top and the memory didn't exceed 40 Gb. I was running it on ec2 instance with 72 Gb of RAM. I am attaching a snapshot of top for reference. 
![kallistoMemory](https://user-images.githubusercontent.com/12998572/68988089-15fac680-0800-11ea-9cf1-217b0432c671.PNG)

**Comment by Lioscro** [comment]
Then memory is most likely not the issue.
Could you try re-running with the `--verbose` flag and post the output here?

**Comment by Lioscro** [comment]
I just ran it on my Windows machine with 32GB memory, and I am getting
```
[build] loading fasta file .\combined.fa
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 771 target sequences
[build] warning: replaced 3762965 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
which may or may not be the same issue.

**Comment by Gaura** [comment]
Thank you for your relies. I tried increasing the memory to 144 Gb and it ran fine. My index file is 26 Gb, larger than the pre-compiled version, but adata is being generated without any issues. 

Thank you.
