### ISSUE TITLE
Non-zero exit status 1 when using velocity flags.

### ISSUE THREAD

**Issue by miretchin** [pachterlab/kb_python#50]
**When using the velocity flags `--lamanno` and `--nucleus`, I get a non-zero exit status 1, and the analysis doesn't finish.**
Note that this issue does _not_ occur when I remove those flags. When I do that, it appears to finish without issue and the output is not empty. Also, the index is _not_ empty, as suggested in what might be a related issue. For additional context, this is single-nucleus RNA-seq data. Running on a `p3.2xlarge` AWS instance.

**What is the exact command that was run?**
```
 kb count -i index.idx -g transcripts_to_genes.txt -o SRR8528318 -c1 cdna_transcript_to_capture.txt -c2 intron_transcripts_to_capture.txt --filter --keep-tmp --h5ad --lamanno --verbose -x DropSeq ../../func_gen/data/raw/SRR8528318_1.fastq ../../func_gen/data/raw/
SRR8528318_2.fastq
```

**Command output (with `--verbose` flag)**
```
[2019-12-09 23:10:07,776]   DEBUG Printing verbose output
[2019-12-09 23:10:07,776]   DEBUG Creating tmp directory
[2019-12-09 23:10:07,776]   DEBUG Namespace(c1='cdna_transcript_to_capture.txt', c2='intron_transcripts_to_capture.txt', command='count', fastqs=['../../func_gen/data/raw/SRR8528318_1.fastq', '../../func_gen/data/raw/SRR8528318_2.fastq'], filter='bustools', g='transcripts_to_genes.txt', h5ad=True, i='index.idx', keep_tmp=True, lamanno=True, list=False, loom=False, m='4G', nucleus=False, o='SRR8528318', overwrite=False, t=8, verbose=True, w=None, x='DropSeq')
[2019-12-09 23:10:07,776]    INFO Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite.
[2019-12-09 23:10:07,776]    INFO Sorting BUS file SRR8528318/output.bus to tmp/output.s.bus
[2019-12-09 23:10:07,776]   DEBUG /home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools sort -o tmp/output.s.bus -T tmp -t 8 -m 4G SRR8528318/output.bus
[2019-12-09 23:10:11,527]   DEBUG Read in 3435664 BUS records
[2019-12-09 23:10:11,527]    INFO Whitelist not provided
[2019-12-09 23:10:11,527]    INFO Generating whitelist SRR8528318/whitelist.txt from BUS file tmp/output.s.bus
[2019-12-09 23:10:11,528]   DEBUG /home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools whitelist -o SRR8528318/whitelist.txt tmp/output.s.bus
[2019-12-09 23:10:11,573]   DEBUG Read in 3137746 BUS records, wrote 22397 barcodes to whitelist with threshold 13
[2019-12-09 23:10:11,573]    INFO Inspecting BUS file tmp/output.s.bus
[2019-12-09 23:10:11,573]   DEBUG /home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools inspect -o SRR8528318/inspect.json -w SRR8528318/whitelist.txt -e SRR8528318/matrix.ec tmp/output.s.bus
[2019-12-09 23:10:23,628]    INFO Correcting BUS records in tmp/output.s.bus to tmp/output.s.c.bus with whitelist SRR8528318/whitelist.txt
[2019-12-09 23:10:23,629]   DEBUG /home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools correct -o tmp/output.s.c.bus -w SRR8528318/whitelist.txt tmp/output.s.bus
[2019-12-09 23:10:24,039]   DEBUG Found 22397 barcodes in the whitelist
[2019-12-09 23:10:24,040]   DEBUG Number of hamming dist 1 barcodes = 886294
[2019-12-09 23:10:24,040]   DEBUG Processed 3137746 bus records
[2019-12-09 23:10:24,040]   DEBUG In whitelist = 414442
[2019-12-09 23:10:24,040]   DEBUG Corrected = 213006
[2019-12-09 23:10:24,040]   DEBUG Uncorrected = 2510298
[2019-12-09 23:10:24,040]    INFO Sorting BUS file tmp/output.s.c.bus to SRR8528318/output.unfiltered.bus
[2019-12-09 23:10:24,040]   DEBUG /home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools sort -o SRR8528318/output.unfiltered.bus -T tmp -t 8 -m 4G tmp/output.s.c.bus
[2019-12-09 23:10:27,062]   DEBUG Read in 627448 BUS records
[2019-12-09 23:10:27,063]    INFO Capturing records from BUS file SRR8528318/output.unfiltered.bus to tmp/spliced.bus with capture list cdna_transcript_to_capture.txt
[2019-12-09 23:10:27,063]   DEBUG /home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools capture -o tmp/spliced.bus -c cdna_transcript_to_capture.txt -e SRR8528318/matrix.ec -t SRR8528318/transcripts.txt --transcripts SRR8528318/output.unfiltered.bus
[2019-12-09 23:10:27,066]   DEBUG Usage: bustools text [options] bus-files
[2019-12-09 23:10:27,066]   DEBUG
[2019-12-09 23:10:27,066]   DEBUG Options:
[2019-12-09 23:10:27,066]   DEBUG -o, --output          File for text output
[2019-12-09 23:10:27,066]   DEBUG -p, --pipe            Write to standard output
[2019-12-09 23:10:27,067]   DEBUG
[2019-12-09 23:10:27,067]   DEBUG Error: File not found, cdna_transcript_to_capture.txt
[2019-12-09 23:10:27,067]   ERROR An exception occurred
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/count.py", line 726, in count_velocity
    bus_result['ecmap'], bus_result['txnames']
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/count.py", line 228, in bustools_capture
    run_executable(command)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/ubuntu/anaconda3/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools capture -o tmp/spliced.bus -c cdna_transcript_to_capture.txt -e SRR8528318/matrix.ec -t SRR8528318/transcripts.txt --transcripts SRR8528318/output.unfiltered.bus' returned non-zero exit status 1.
```

I would really appreciate your help with this, as I am very excited to try using velocity with `kb`. Thank you for your time!

**Comment by miretchin** [comment]
I misspelled `cdna_transcript*s*_to_capture.txt` in my command. It just finished running without issue.
