### ISSUE TITLE
Non-zero Exit Status 3221225477.

### ISSUE THREAD

**Issue by basilkhuder** [pachterlab/kb_python#58]
KB-python fails when it gets to the sorting step. I ran it with --verbose, as shown below and with --lamanno for Velocity. In addition, regardless of whether I input my own barcodes are use the default whitelist, the issue persists. I see that it's stating `DEBUG Read in 0 BUS records` so I'm curious if it's unable to read in the BUS file produced in the step before. 

```
[2020-02-06 12:11:15,758]   DEBUG Printing verbose output
[2020-02-06 12:11:15,758]   DEBUG Creating tmp directory
[2020-02-06 12:11:15,759]   DEBUG Namespace(c1='spliced_t2c.txt', c2='unspliced_t2c.txt', command='count', fastqs=['nuclei_900_S1_L001_R1_001.fastq.gz', 'nuclei_900_S1_L001_R2_001.fastq.gz'], filter=None, g='t2g.txt', h5ad=False, i='index.idx', keep_tmp=True, lamanno=True, list=False, loom=False, m='4G', nucleus=False, o='out', overwrite=True, t=2, verbose=True, w='barcodes.txt', x='10XV2')
[2020-02-06 12:11:15,759]    INFO Generating BUS file from
[2020-02-06 12:11:15,759]    INFO         nuclei_900_S1_L001_R1_001.fastq.gz
[2020-02-06 12:11:15,759]    INFO         nuclei_900_S1_L001_R2_001.fastq.gz
[2020-02-06 12:11:15,759]   DEBUG c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\bins\windows\kallisto\kallisto.exe bus -i index.idx -o out -x 10XV2 -t 2 nuclei_900_S1_L001_R1_001.fastq.gz nuclei_900_S1_L001_R2_001.fastq.gz
[2020-02-06 12:16:46,896]   DEBUG 
[2020-02-06 12:16:46,896]   DEBUG [index] k-mer length: 31
[2020-02-06 12:16:46,896]   DEBUG [index] number of targets: 845,338
[2020-02-06 12:16:46,896]   DEBUG [index] number of k-mers: 271,648,279
[2020-02-06 12:16:46,896]   DEBUG [index] number of equivalence classes: 4,776,424
[2020-02-06 12:16:46,896]   DEBUG [quant] will process sample 1: nuclei_900_S1_L001_R1_001.fastq.gz
[2020-02-06 12:16:46,896]   DEBUG nuclei_900_S1_L001_R2_001.fastq.gz
[2020-02-06 12:16:46,896]   DEBUG [quant] finding pseudoalignments for the reads ... done
[2020-02-06 12:16:46,896]   DEBUG [quant] processed 24,393,189 reads, 3,476,240 reads pseudoaligned
[2020-02-06 12:16:46,943]    INFO Sorting BUS file out\output.bus to tmp\output.s.bus
[2020-02-06 12:16:46,943]   DEBUG c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o tmp\output.s.bus -T tmp -t 2 -m 4G out\output.bus
[2020-02-06 12:16:49,176]   DEBUG Read in 0 BUS records
[2020-02-06 12:16:49,176]   ERROR An exception occurred
Traceback (most recent call last):
  File "c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\main.py", line 120, in parse_count
    count_velocity(
  File "c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\count.py", line 684, in count_velocity
    sort_result = bustools_sort(
  File "c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\count.py", line 97, in bustools_sort
    run_executable(command)
  File "c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command 'c:\users\user1\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o tmp\output.s.bus -T tmp -t 2 -m 4G out\output.bus' returned non-zero exit status 32212
```25477.

**Comment by Lioscro** [comment]
Bustools crashes if it tries to read a BUS file with no BUS records (this will give a more informative error in the next version).
Though I am not sure why the BUS file is empty...

**Comment by basilkhuder** [comment]
> Bustools crashes if it tries to read a BUS file with no BUS records (this will give a more informative error in the next version).
> Though I am not sure why the BUS file is empty...

Not sure either. When I look at the output.bus file, I can clearly see that it's 100mb. I may just run the sort step separately using BUSTools until I can figure this out.
