### ISSUE TITLE
ValueError: could not convert integer scalar

### ISSUE THREAD

**Issue by Acribbs** [pachterlab/kb_python#60]
Hi developers, fantastic tool! 

I am unable to run kb count because of an error during the combining of matrices. Im going through the exact piece of code in count.py so I can debug but still not completely clear to me the issue. Any help would be much appreciated.

kb-python=0.24.4

Not sure if its my data because the test data from google colab kb tutorials (using kb_single_nucleus.ipynb) worked well.

**What is the exact command that was run?**
```
kb ref -i geneset.dir/index.idx -g geneset.dir/t2g.txt -f1 geneset.dir/cdna.fa     -f2 geneset.dir/intron.fa -c1 geneset.dir/cdna_t2c.txt -c2 geneset.dir/intron_t2c.txt     --workflow nucleus -n 8

 kb count -i geneset.dir/index.idx.7,geneset.dir/index.idx.5,geneset.dir/index.idx.0,geneset.dir/index.idx.2,geneset.dir/index.idx.6,geneset.dir/index.idx.1,geneset.dir/index.idx.3,geneset.dir/index.idx.4 -g geneset.dir/t2g.txt      -c1 geneset.dir/cdna_t2c.txt -c2 geneset.dir/intron_t2c.txt -x DropSeq     -o kallisto.dir/D145E_S1/bus --workflow nucleus --loom  ./D145E_S1.fastq.1.gz ./D145E_S1.fastq.2.gz     2> kallisto.dir/D145E_S1/bus_kblog.log

```

**Command output (with `--verbose` flag)**
```
[2020-02-19 10:16:30,772]    INFO Generating BUS file using 8 indices
[2020-02-19 10:16:30,774]    INFO Using index geneset.dir/index.idx.7 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part0 from
[2020-02-19 10:16:30,774]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 10:16:30,774]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 10:26:51,439]    INFO Using index geneset.dir/index.idx.5 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part1 from
[2020-02-19 10:26:51,440]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 10:26:51,440]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 10:38:26,428]    INFO Using index geneset.dir/index.idx.0 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part2 from
[2020-02-19 10:38:26,428]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 10:38:26,428]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 10:48:32,959]    INFO Using index geneset.dir/index.idx.2 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part3 from
[2020-02-19 10:48:32,959]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 10:48:32,959]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 10:59:08,434]    INFO Using index geneset.dir/index.idx.6 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part4 from
[2020-02-19 10:59:08,434]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 10:59:08,434]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 11:09:18,015]    INFO Using index geneset.dir/index.idx.1 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part5 from
[2020-02-19 11:09:18,016]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 11:09:18,016]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 11:19:25,219]    INFO Using index geneset.dir/index.idx.3 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part6 from
[2020-02-19 11:19:25,220]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 11:19:25,220]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 11:30:02,210]    INFO Using index geneset.dir/index.idx.4 to generate BUS file to kallisto.dir/./D145E_S1/bus/tmp/bus_part7 from
[2020-02-19 11:30:02,210]    INFO         ./D145E_S1.fastq.1.gz
[2020-02-19 11:30:02,210]    INFO         ./D145E_S1.fastq.2.gz
[2020-02-19 11:40:19,338]    INFO Merging BUS records to kallisto.dir/./D145E_S1/bus from
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part0
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part1
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part2
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part3
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part4
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part5
[2020-02-19 11:40:19,338]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part6
[2020-02-19 11:40:19,339]    INFO         kallisto.dir/./D145E_S1/bus/tmp/bus_part7
[2020-02-19 11:58:06,904]    INFO Sorting BUS file kallisto.dir/./D145E_S1/bus/output.bus to kallisto.dir/./D145E_S1/bus/tmp/output.s.bus
[2020-02-19 12:00:53,974]    INFO Whitelist not provided
[2020-02-19 12:00:53,975]    INFO Generating whitelist kallisto.dir/./D145E_S1/bus/whitelist.txt from BUS file kallisto.dir/./D145E_S1/bus/tmp/output.s.bus
[2020-02-19 12:00:55,186]    INFO Inspecting BUS file kallisto.dir/./D145E_S1/bus/tmp/output.s.bus
[2020-02-19 12:07:44,273]    INFO Correcting BUS records in kallisto.dir/./D145E_S1/bus/tmp/output.s.bus to kallisto.dir/./D145E_S1/bus/tmp/output.s.c.bus with whitelist kallisto.dir/./D145E_S1/bus/whitelist.txt
[2020-02-19 12:08:12,843]    INFO Sorting BUS file kallisto.dir/./D145E_S1/bus/tmp/output.s.c.bus to kallisto.dir/./D145E_S1/bus/output.unfiltered.bus
[2020-02-19 12:09:15,982]    INFO Capturing records from BUS file kallisto.dir/./D145E_S1/bus/output.unfiltered.bus to kallisto.dir/./D145E_S1/bus/tmp/spliced.bus with capture list geneset.dir/intron_t2c.txt
[2020-02-19 12:16:48,559]    INFO Sorting BUS file kallisto.dir/./D145E_S1/bus/tmp/spliced.bus to kallisto.dir/./D145E_S1/bus/spliced.unfiltered.bus
[2020-02-19 12:16:53,730]    INFO Inspecting BUS file kallisto.dir/./D145E_S1/bus/spliced.unfiltered.bus
[2020-02-19 12:22:22,623]    INFO Generating count matrix kallisto.dir/./D145E_S1/bus/counts_unfiltered/spliced from BUS file kallisto.dir/./D145E_S1/bus/spliced.unfiltered.bus
[2020-02-19 12:31:42,780]    INFO Capturing records from BUS file kallisto.dir/./D145E_S1/bus/output.unfiltered.bus to kallisto.dir/./D145E_S1/bus/tmp/unspliced.bus with capture list geneset.dir/cdna_t2c.txt
[2020-02-19 12:43:53,306]    INFO Sorting BUS file kallisto.dir/./D145E_S1/bus/tmp/unspliced.bus to kallisto.dir/./D145E_S1/bus/unspliced.unfiltered.bus
[2020-02-19 12:44:31,714]    INFO Inspecting BUS file kallisto.dir/./D145E_S1/bus/unspliced.unfiltered.bus
[2020-02-19 12:50:46,299]    INFO Generating count matrix kallisto.dir/./D145E_S1/bus/counts_unfiltered/unspliced from BUS file kallisto.dir/./D145E_S1/bus/unspliced.unfiltered.bus
[2020-02-19 13:01:39,061]    INFO Reading matrix kallisto.dir/./D145E_S1/bus/counts_unfiltered/spliced.mtx
[2020-02-19 13:01:43,009]    INFO Reading matrix kallisto.dir/./D145E_S1/bus/counts_unfiltered/unspliced.mtx
[2020-02-19 13:01:47,348]    INFO Combining matrices
[2020-02-19 13:13:45,216]   ERROR An exception occurred
Traceback (most recent call last):
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/kb_python/main.py", line 697, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/kb_python/main.py", line 194, in parse_count
    temp_dir=temp_dir
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/kb_python/count.py", line 1297, in count_velocity
    nucleus=nucleus
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/kb_python/count.py", line 584, in convert_matrices
    adata = sum_anndatas(*adatas) if nucleus else overlay_anndatas(*adatas)
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/kb_python/utils.py", line 681, in sum_anndatas
    spliced_unspliced = spliced_intersection.copy()
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/anndata/_core/anndata.py", line 1425, in copy
    X = _subset(self._adata_ref.X, (self._oidx, self._vidx)).copy()
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/functools.py", line 827, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/anndata/_core/index.py", line 126, in _subset
    return a[subset_idx]
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/scipy/sparse/_index.py", line 75, in __getitem__
    return self._get_arrayXarray(row, col)
  File "/ifs/devel/adamc/cgat-developers/conda-install/envs/single-cell/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 665, in _get_arrayXarray
    major.size, major.ravel(), minor.ravel(), val)
ValueError: could not convert integer scalar
```

**Comment by Lioscro** [comment]
Hi, @Acribbs,
It seems to me you are using a development version of `kb`!
I've made a slight change to how anndatas are summed in commit a23aae55dacb4ef46d5210dbfb9d060da795696c.
You can install it by running the following command
```
pip install git+https://github.com/pachterlab/kb_python@count-kite
```

Please let me know if that fixes the issue.

**Comment by Acribbs** [comment]
Despite updating the software to the lastest code this didn't solve my problem.

However, I investigated further and found that this sample was sequenced incredibly high number of reads (>400 million) because of human error (Only one sample added to library pool).

I think the cryptic error relates to exhausting the vector memory limit because I cant see any issue in the underlying code, but when I downsample the fastq files this error disappears. I could be wrong about there not being any specific bug though because scipy code is quite bloated and difficult to follow in parts.

I will close this issue now. Thanks for your help and great work!
