### ISSUE TITLE
kb count Being SIGKILL'd at bustools sort Step

### ISSUE THREAD

**Issue by jggatter** [pachterlab/kb_python#64]
**Describe the issue**
Hi I'm running kb count in a Docker image being run on Cromwell and Google Cloud Platform and the command (below) is SIGKILL'd at the bustools sort step. It seems to me that it is happening when it is building the command for bustools sort.
[Docker image](https://hub.docker.com/repository/docker/shaleklab/kallisto-bustools)
[WDL script](https://portal.firecloud.org/#methods/alexandria_dev/kallisto-bustools_count/24)

**What is the exact command that was run?**
For context, here are my disks (df -h)
```
Filesystem                         Size  Used Avail Use% Mounted on
overlay                             96G  2.3G   93G   3% /
tmpfs                               64M     0   64M   0% /dev
tmpfs                              126G     0  126G   0% /sys/fs/cgroup
shm                                 64M     0   64M   0% /dev/shm
/dev/sda1                           96G  2.3G   93G   3% /google
/dev/disk/by-id/google-local-disk  251G   26G  226G  11% /cromwell_root
tmpfs                              126G     0  126G   0% /proc/acpi
tmpfs                              126G     0  126G   0% /proc/scsi
tmpfs                              126G     0  126G   0% /sys/firmware
```
And here is the command:
```
#pwd is /cromwell_root
set -e
export TMPDIR=/tmp

kb count --verbose \
	-i /cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/index.idx \
	-g /cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/transcripts_to_genes.txt \
	-x DROPSEQ \
	-o count_CGP \
	 \
	--lamanno \
	-c1 /cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/cDNA_transcripts_to_capture.txt \
	-c2 /cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/intron_transcripts_to_capture.txt \
	 \
	--filter bustools \
	 \
	 \
	-t 32 \
	-m 256G \
	$(cat fastqs.tsv)
```
fastqs.tsv contains space-delimited FASTQ filenames (e.g."CGP_R1.fastq.gz CGP_R2.fastq.gz" which are located in the present working directory)

**Command output (with `--verbose` flag)**
```
CGP_R1.fastq.gz CGP_R2.fastq.gz[2020-03-30 15:58:59,055]   DEBUG Printing verbose output
[2020-03-30 15:58:59,055]   DEBUG Creating tmp directory
[2020-03-30 15:58:59,056]   DEBUG Namespace(c1='/cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/cDNA_transcripts_to_capture.txt', c2='/cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/intron_transcripts_to_capture.txt', command='count', fastqs=['CGP_R1.fastq.gz', 'CGP_R2.fastq.gz'], filter='bustools', g='/cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/transcripts_to_genes.txt', h5ad=False, i='/cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/index.idx', keep_tmp=False, lamanno=True, list=False, loom=False, m='256G', nucleus=False, o='count_CGP', overwrite=False, t=32, verbose=True, w=None, x='DROPSEQ')
[2020-03-30 15:58:59,057]    INFO Generating BUS file from
[2020-03-30 15:58:59,057]    INFO         CGP_R1.fastq.gz
[2020-03-30 15:58:59,057]    INFO         CGP_R2.fastq.gz
[2020-03-30 15:58:59,057]   DEBUG /usr/local/lib/python3.7/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i /cromwell_root/shalek-lab-cromwell/kallisto-bustools/jobs/testkb4/ref/index.idx -o count_CGP -x DROPSEQ -t 32 CGP_R1.fastq.gz CGP_R2.fastq.gz
[2020-03-30 16:17:38,738]   DEBUG 
[2020-03-30 16:17:38,738]   DEBUG [index] k-mer length: 31
[2020-03-30 16:17:38,738]   DEBUG [index] number of targets: 790,418
[2020-03-30 16:17:38,738]   DEBUG [index] number of k-mers: 1,112,132,904
[2020-03-30 16:17:38,738]   DEBUG [index] number of equivalence classes: 5,486,663
[2020-03-30 16:17:38,738]   DEBUG [quant] will process sample 1: CGP_R1.fastq.gz
[2020-03-30 16:17:38,738]   DEBUG CGP_R2.fastq.gz
[2020-03-30 16:17:38,738]   DEBUG [quant] finding pseudoalignments for the reads ... done
[2020-03-30 16:17:38,738]   DEBUG [quant] processed 254,495,575 reads, 193,336,101 reads pseudoaligned
[2020-03-30 16:17:38,739]    INFO Sorting BUS file count_CGP/output.bus to tmp/output.s.bus
[2020-03-30 16:17:38,739]   DEBUG /usr/local/lib/python3.7/site-packages/kb_python/bins/linux/bustools/bustools sort -o tmp/output.s.bus -T tmp -t 32 -m 256G count_CGP/output.bus
[2020-03-30 16:20:45,441]   ERROR An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/usr/local/lib/python3.7/site-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
  File "/usr/local/lib/python3.7/site-packages/kb_python/count.py", line 689, in count_velocity
    memory=memory
  File "/usr/local/lib/python3.7/site-packages/kb_python/count.py", line 97, in bustools_sort
    run_executable(command)
  File "/usr/local/lib/python3.7/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/usr/local/lib/python3.7/site-packages/kb_python/bins/linux/bustools/bustools sort -o tmp/output.s.bus -T tmp -t 32 -m 256G count_CGP/output.bus' died with <Signals.SIGKILL: 9>.
[2020-03-30 16:20:45,634]   DEBUG Removing tmp directory
```
Furthermore, although I do not think memory is the problem, the monitoring log shows that the memory usage skyrocketed to 95% around this time (perhaps to delete the tmp dir?):
```
[Mon Mar 30 16:20:01 UTC 2020]
* CPU usage: 2.84003%
* Memory usage: 76.31%
* Disk usage: 19%
[Mon Mar 30 16:20:31 UTC 2020]
* CPU usage: 3.04777%
* Memory usage: 95.0675%
* Disk usage: 19%
```
Please help me figure out why the command is being killed. Perhaps the subprocess.CallProcessError contains a hint but is not outputting anything descriptive? Thank you!

edit: I should also say that the error exits with a return code of 0 somehow

**Comment by Lioscro** [comment]
We've experienced exit status 9 when the system runs out of memory, and this seems to be the case, seeing the memory usage you posted. I think the easiest way to solve this would be to increase the allocated memory.

**Comment by jggatter** [comment]
Hi Joseph,

I've tried running with 512 GB and that didn't fix the problem. Surely
that's excessive anyways for a program that people can run on their local
machines? What do you suggest? 1 TB RAM?

James

**Comment by Lioscro** [comment]
Indeed, it's odd that sort is being killed by the OS for running out of memory, as that command should always yield to the `-m` option. May I ask how much RAM is allocated to the google cloud instance?

**Comment by jggatter** [comment]
In my monitoring log, it seems Google rounds up to 530GB. Yeah this is weird. I don't think the boot disk size for the Docker image has much impact, but as tweaking it has given me some success in the past I'm going to try increasing it (it's already at 100GB which is already excessive).
 ```
==================================
=========== MONITORING ===========
==================================
--- General Information ---
#CPU: 80
Total Memory: 528.382G
Total Disk space: 251G
```
I'll let you know how that goes!

Thanks for your time!
James

**Comment by Lioscro** [comment]
Could you try running with the same amount of memory (512GB) to the instance but change the `kb` command memory limit to be something less than that (perhaps 256GB)? In this case, there would be 256GB memory free.

Since `kb` runs  and `bustools` binary in the background, both `kb` and `bustools` needs sufficient memory to run. In your case, `bustools` is attempting to use all 512GB of memory, while `kb` is also using a portion of that memory.

**Comment by jggatter** [comment]
Your suggestion worked!!! Thank you so much, Joseph!

So if I have a user give their task X GB of memory, do you know what the maximum memory I can give to kb python is without having it get SIGKILL signaled?

**Comment by Lioscro** [comment]
Glad that it worked!
I don't know how much memory `kb` itself uses, as I have not benchmarked its memory usage alone.
Keep in mind that processes other than `kb` may be using some amount of RAM, which is an additional reason to have the `-m` argument lower than the maximum RAM of the system.

**Comment by jggatter** [comment]
Okay, will keep that in mind! Thanks again!
