### ISSUE TITLE
kb ref doesn't support gff and has no readable message about it

### ISSUE THREAD

**Issue by ArtyomKaltovich** [pachterlab/kb_python#66]
Hello. Thank you for your tools.

As I got it kb doesn't support gff files for now.

**What is the exact command that was run?**
```
kb ref -i transcriptome.idx -g transcripts_to_genes.txt -f1 cdna.fa dna.primary_assembly.fa.gz gtf.gz
```

**Command output**
```
[2020-04-15 16:55:38,254]   ERROR An exception occurred
Traceback (most recent call last):
  File "/home/my/.local/lib/python3.8/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/home/my/.local/lib/python3.8/site-packages/kb_python/main.py", line 103, in parse_ref
    ref(
  File "/home/my/.local/lib/python3.8/site-packages/kb_python/ref.py", line 273, in ref
    t2g_result = create_t2g_from_gtf(gtf_path, t2g_path)
  File "/home/my/.local/lib/python3.8/site-packages/kb_python/ref.py", line 105, in create_t2g_from_gtf
    transcript_id = entry['group']['transcript_id']
KeyError: 'transcript_id'
```

Could you add gff support or at lease create more readable error message?

Regards,
Artyom.

**Comment by ArtyomKaltovich** [comment]
Hello. 

If I correctly got the error's reason I can add error message by myself.

**Comment by Lioscro** [comment]
Hi, @ArtyomKaltovich,
I think a `transcript` entry in your GTF file is missing a `transcript_id` group (in the last column of the GTF). Without that, it isn't possible to create a transcript-to-gene mapping.
Could you check if that is the issue?

**Comment by ArtyomKaltovich** [comment]
Hello @Lioscro.

I run kb for gff file, as I got they are not supported for now, but it hard to understand with such error, could you add more readable error message.

Thank you.
