### ISSUE TITLE
kb count returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by pchiang5** [pachterlab/kb_python#67]
When I input the following code in miniconda3 of windows10:

`kb count -i "M:\My Drive\tools\kallisto\intron\index.idx" -m 100000000 --overwrite  -g t2g.txt -c1 cdna_t2c.txt -c2 intron_t2c.txt -o bus_output -x  0,0,12:0,12,24:1,0,0 -t 24 --lamanno --h5ad --verbose --filter bustools BCUMI.gz fixed_R1_50.gz
`

It showed the error below:

> 
> c:\programdata\miniconda3\lib\site-packages\anndata\_core\anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
>   from pandas.core.index import RangeIndex
> [2020-04-15 12:18:46,979]   DEBUG Printing verbose output
> [2020-04-15 12:18:46,979]   DEBUG Creating tmp directory
> [2020-04-15 12:18:46,979]   DEBUG Namespace(c1='cdna_t2c.txt', c2='intron_t2c.txt', command='count', fastqs=['BCUMI.gz', 'fixed_R1_50.gz'], filter='bustools', g='t2g.txt', h5ad=True, i='M:\\My Drive\\tools\\kallisto\\intron\\index.idx', keep_tmp=False, lamanno=True, list=False, loom=False, m='100000000', nucleus=False, o='bus_output', overwrite=True, t=24, verbose=True, w=None, x='0,0,12:0,12,24:1,0,0')
> [2020-04-15 12:18:46,979]    INFO Generating BUS file from
> [2020-04-15 12:18:46,979]    INFO         BCUMI.gz
> [2020-04-15 12:18:46,979]    INFO         fixed_R1_50.gz
> [2020-04-15 12:18:46,979]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\kallisto\kallisto.exe bus -i M:\My Drive\tools\kallisto\intron\index.idx -o bus_output -x 0,0,12:0,12,24:1,0,0 -t 24 BCUMI.gz fixed_R1_50.gz
> [2020-04-15 22:28:00,962]   DEBUG
> [2020-04-15 22:28:00,963]   DEBUG [index] k-mer length: 31
> [2020-04-15 22:28:00,963]   DEBUG [index] number of targets: 2,080,292
> [2020-04-15 22:28:00,964]   DEBUG [index] number of k-mers: 2,670,597,649
> [2020-04-15 22:28:00,964]   DEBUG [index] number of equivalence classes: 18,250,913
> [2020-04-15 22:28:00,965]   DEBUG [quant] will process sample 1: BCUMI.gz
> [2020-04-15 22:28:00,966]   DEBUG fixed_R1_50.gz
> [2020-04-15 22:28:00,967]   DEBUG [quant] finding pseudoalignments for the reads ... done
> [2020-04-15 22:28:00,968]   DEBUG [quant] processed 63,142,586 reads, 51,961,068 reads pseudoaligned
> [2020-04-15 22:28:02,139]    INFO Sorting BUS file bus_output\output.bus to tmp\output.s.bus
> [2020-04-15 22:28:02,140]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o tmp\output.s.bus -T tmp -t 24 -m 100000000 bus_output\output.bus
> [2020-04-15 23:18:16,381]   DEBUG Read in 51961068 BUS records
> [2020-04-15 23:18:16,382]    INFO Whitelist not provided
> [2020-04-15 23:18:16,383]    INFO Generating whitelist bus_output\whitelist.txt from BUS file tmp\output.s.bus
> [2020-04-15 23:18:16,384]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe whitelist -o bus_output\whitelist.txt tmp\output.s.bus
> [2020-04-15 23:18:22,288]   DEBUG Read in 48485010 BUS records, wrote 60882 barcodes to whitelist with threshold 122
> [2020-04-15 23:18:22,289]    INFO Inspecting BUS file tmp\output.s.bus
> [2020-04-15 23:18:22,292]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe inspect -o bus_output\inspect.json -w bus_output\whitelist.txt -e bus_output\matrix.ec tmp\output.s.bus
> [2020-04-16 00:38:01,889]    INFO Correcting BUS records in tmp\output.s.bus to tmp\output.s.c.bus with whitelist bus_output\whitelist.txt
> [2020-04-16 00:38:01,891]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe correct -o tmp\output.s.c.bus -w bus_output\whitelist.txt tmp\output.s.bus
> [2020-04-16 00:50:02,128]   DEBUG Found 60881 barcodes in the whitelist
> [2020-04-16 00:50:02,129]   DEBUG Number of hamming dist 1 barcodes = 793266
> [2020-04-16 00:50:02,130]   DEBUG Processed 48485010 bus records
> [2020-04-16 00:50:02,131]   DEBUG In whitelist = 26843542
> [2020-04-16 00:50:02,132]   DEBUG Corrected = 5521574
> [2020-04-16 00:50:02,132]   DEBUG Uncorrected = 16119894
> [2020-04-16 00:50:02,133]    INFO Sorting BUS file tmp\output.s.c.bus to bus_output\output.unfiltered.bus
> [2020-04-16 00:50:02,134]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o bus_output\output.unfiltered.bus -T tmp -t 24 -m 100000000 tmp\output.s.c.bus
> [2020-04-16 01:26:02,989]   DEBUG Read in 32365116 BUS records
> [2020-04-16 01:26:02,992]    INFO Capturing records from BUS file bus_output\output.unfiltered.bus to tmp\spliced.bus with capture list cdna_t2c.txt
> [2020-04-16 01:26:02,993]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe capture -o tmp\spliced.bus -c cdna_t2c.txt -e bus_output\matrix.ec -t bus_output\transcripts.txt --transcripts bus_output\output.unfiltered.bus
> [2020-04-16 03:03:44,511]   DEBUG Parsing transcripts .. done
> [2020-04-16 03:03:44,511]   DEBUG Parsing ECs .. done
> [2020-04-16 03:03:44,513]   DEBUG Parsing capture list .. done
> [2020-04-16 03:03:44,514]   DEBUG Read in 32226847 BUS records, wrote 19893640 BUS records
> [2020-04-16 03:03:45,004]    INFO Sorting BUS file tmp\spliced.bus to bus_output\spliced.unfiltered.bus
> [2020-04-16 03:03:45,005]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe sort -o bus_output\spliced.unfiltered.bus -T tmp -t 24 -m 100000000 tmp\spliced.bus
> [2020-04-16 03:21:37,083]   DEBUG Read in 19907597 BUS records
> [2020-04-16 03:21:37,084]    INFO Generating count matrix bus_output\counts_unfiltered\spliced from BUS file bus_output\spliced.unfiltered.bus
> [2020-04-16 03:21:37,086]   DEBUG c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe count -o bus_output\counts_unfiltered\spliced -g t2g.txt -e bus_output\matrix.ec -t bus_output\transcripts.txt --genecounts bus_output\spliced.unfiltered.bus
> [2020-04-16 04:43:14,841]   ERROR An exception occurred
> Traceback (most recent call last):
>   File "c:\programdata\miniconda3\lib\site-packages\kb_python\main.py", line 483, in main
>     COMMAND_TO_FUNCTION[args.command](args)
>   File "c:\programdata\miniconda3\lib\site-packages\kb_python\main.py", line 135, in parse_count
>     nucleus=args.nucleus,
>   File "c:\programdata\miniconda3\lib\site-packages\kb_python\count.py", line 746, in count_velocity
>     bus_result['txnames'],
>   File "c:\programdata\miniconda3\lib\site-packages\kb_python\count.py", line 181, in bustools_count
>     run_executable(command)
>   File "c:\programdata\miniconda3\lib\site-packages\kb_python\utils.py", line 147, in run_executable
>     raise sp.CalledProcessError(p.returncode, ' '.join(command))
> subprocess.CalledProcessError: Command 'c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe count -o bus_output\counts_unfiltered\spliced -g t2g.txt -e bus_output\matrix.ec -t bus_output\transcripts.txt --genecounts bus_output\spliced.unfiltered.bus' returned non-zero exit status 3221225477.
> [2020-04-16 04:43:14,884]   DEBUG Removing tmp directory

However, the last step ran fine when it was input alone:

`c:\programdata\miniconda3\lib\site-packages\kb_python\bins\windows\bustools\bustools.exe count -o bus_output\counts_unfiltered\spliced -g t2g.txt -e bus_output\matrix.ec -t bus_output\transcripts.txt --genecounts bus_output\spliced.unfiltered.bus`

What could be the potential cause? If the problem cannot be resolved, how shall I continue the analysis with the output already there?  Thanks.

**Comment by pchiang5** [comment]
Update:

The identical input finished well with WSL1. Probably there was an incompatibility between my fastq files and the native windows version of bustools.
