### ISSUE TITLE
kb-python of 10X v1 data dies with Signals.SIGSEGV:11

### ISSUE THREAD

**Issue by davisidarta** [pachterlab/kb_python#71]
**Describe the issue**
A clear and concise description of what the issue is.

I'm trying to run kb-python in 10X v1 data. I've previously runner kb on drop-seq and 10X v2 data. However, with 2 different 10X v1 experiments downloaded with `fastq-dump --split-files `, running kb leads me to an error:

**What is the exact command that was run?**
```
kb count --verbose -i index.idx -g transcripts_to_genes.txt -x 10XV1 -o Sample2_1 -c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt --lamanno --loom SRR8571786_1.fastq SRR8571786_2.fastq SRR8571786_3.fastq

```

**Command output (with `--verbose` flag)**
```

/usr/local/lib/python3.7/dist-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
[2020-05-03 19:45:20,534]   DEBUG Printing verbose output
[2020-05-03 19:45:20,534]   DEBUG Creating tmp directory
[2020-05-03 19:45:20,534]   DEBUG Namespace(c1='cdna_transcripts_to_capture.txt', c2='intron_transcripts_to_capture.txt', command='count', fastqs=['SRR8571786_1.fastq', 'SRR8571786_2.fastq', 'SRR8571786_3.fastq'], filter=None, g='transcripts_to_genes.txt', h5ad=False, i='index.idx', keep_tmp=False, lamanno=True, list=False, loom=True, m='4G', nucleus=False, o='Sample2_1', overwrite=False, t=8, verbose=True, w=None, x='10XV1')
[2020-05-03 19:45:20,534]    INFO Generating BUS file from
[2020-05-03 19:45:20,534]    INFO         SRR8571786_1.fastq
[2020-05-03 19:45:20,534]    INFO         SRR8571786_2.fastq
[2020-05-03 19:45:20,534]    INFO         SRR8571786_3.fastq
[2020-05-03 19:45:20,534]   DEBUG /usr/local/lib/python3.7/dist-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o Sample2_1 -x 10XV1 -t 8 SRR8571786_1.fastq SRR8571786_2.fastq SRR8571786_3.fastq

[2020-05-03 19:48:31,342]   DEBUG 
[2020-05-03 19:48:31,343]   DEBUG [index] k-mer length: 31
[2020-05-03 19:48:31,343]   DEBUG [index] number of targets: 790,418
[2020-05-03 19:48:31,343]   DEBUG [index] number of k-mers: 1,112,132,904
[2020-05-03 19:48:31,343]   DEBUG [index] number of equivalence classes: 5,486,663
[2020-05-03 19:48:31,343]   DEBUG [quant] will process sample 1: SRR8571786_1.fastq
[2020-05-03 19:48:31,343]   DEBUG SRR8571786_2.fastq
[2020-05-03 19:48:31,343]   DEBUG SRR8571786_3.fastq
[2020-05-03 19:48:31,343]   DEBUG [quant] finding pseudoalignments for the reads ...
[2020-05-03 19:48:31,343]   ERROR An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/usr/local/lib/python3.7/dist-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
  File "/usr/local/lib/python3.7/dist-packages/kb_python/count.py", line 676, in count_velocity
    fastqs, index_path, technology, out_dir, threads=threads
  File "/usr/local/lib/python3.7/dist-packages/kb_python/count.py", line 65, in kallisto_bus
    run_executable(command)
  File "/usr/local/lib/python3.7/dist-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/usr/local/lib/python3.7/dist-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o Sample2_1 -x 10XV1 -t 8 SRR8571786_1.fastq SRR8571786_2.fastq SRR8571786_3.fastq' died with <Signals.SIGSEGV: 11>.
```
 I've redownloaded data and still have the same output. The output.bus file is empty.

Any clues?

**Comment by Lioscro** [comment]
HI @davisidarta,

Could you try double checking each of the fastqs?
For 10xv1, the FASTQs need to be provided in the following order:
1. The first fastq must contain the 14-bp cell barcodes
2. The second fastq must contain the 10-bp UMIs
3. The third fastq must contain the cDNA reads
