### ISSUE TITLE
returned non-zero exit status 1 error

### ISSUE THREAD

**Issue by marttty** [pachterlab/kb_python#75]
Hi I would like to run a kallisto and bustolls analyze on my data at university server , however, I always got this error.

[ts15433@bp1-login01 ts15433]$ kb count --overwrite --h5ad -i index.idx -g t2g.txt -x 10XV1 -o output --filter bustools -t 2 /work/ts15433/SRR1853178_1.fastq.gz /work/ts15433/SRR1853178_2.fastq.gz

[2020-06-24 19:39:10,280]    INFO Generating BUS file from
[2020-06-24 19:39:10,280]    INFO         /work/ts15433/SRR1853178_1.fastq.gz
[2020-06-24 19:39:10,280]    INFO         /work/ts15433/SRR1853178_2.fastq.gz
[2020-06-24 19:39:10,291]   ERROR An exception occurred
Traceback (most recent call last):
  File "/home/ts15433/.local/lib/python3.7/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/home/ts15433/.local/lib/python3.7/site-packages/kb_python/main.py", line 150, in parse_count
    h5ad=args.h5ad,
  File "/home/ts15433/.local/lib/python3.7/site-packages/kb_python/count.py", line 508, in count
    fastqs, index_path, technology, out_dir, threads=threads
  File "/home/ts15433/.local/lib/python3.7/site-packages/kb_python/count.py", line 65, in kallisto_bus
    run_executable(command)
  File "/home/ts15433/.local/lib/python3.7/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/ts15433/.local/lib/python3.7/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o output -x 10XV1 -t 2 /work/ts15433/SRR1853178_1.fastq.gz /work/ts15433/SRR1853178_2.fastq.gz' returned non-zero exit status 1.

**Comment by trezende21** [comment]
having the same error here
