### ISSUE TITLE
SureCell data crashing at bustools count 

### ISSUE THREAD

**Issue by GabyBG** [pachterlab/kb_python#78]
**Describe the issue**
Hello,

I am working with SureCell single-cell data and I am trying to use kb_python to analyze it. 

I work on a SLURM system
and I have created an environment specific for Python3
My script looks like this:

#!/bin/bash
#SBATCH --job-name=kb
#SBATCH -A SEYEDAM_LAB
#SBATCH --output=kb.out
#SBATCH --error=kb.err
#SBATCH --time=3-00:00:00
#SBATCH --partition=free
#SBATCH --ntasks=20

source conda.sh
kb count -i /share/crsp/lab/seyedam/gbalderr/scBrain/kallisto/gencodeM21_pc_long.idx -g kb_trial.txt -x SURECELL --h5ad -t 20 TLR21_C029_S1_R1.fastq.gz TLR21_C029_S1_R2.fastq.gz

It looks like is running ok, but at the end of my log files I see the error:

data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level names
pace.
  from pandas.core.index import RangeIndex
[2020-08-06 22:53:04,576]    INFO Generating BUS file from
[2020-08-06 22:53:04,577]    INFO TLR21_C029_S1_R1.fastq.gz
[2020-08-06 22:53:04,577]    INFO TLR21_C029_S1_R2.fastq.gz
[2020-08-06 22:56:01,242]    INFO Sorting BUS file ./output.bus to tmp/output.s.bus
[2020-08-06 22:56:13,889]    INFO Whitelist not provided
[2020-08-06 22:56:13,889]    INFO Generating whitelist ./whitelist.txt from BUS file tmp/output.s.bus
[2020-08-06 22:56:13,985]    INFO Inspecting BUS file tmp/output.s.bus
[2020-08-06 22:56:14,653]    INFO Correcting BUS records in tmp/output.s.bus to tmp/output.s.c.bus with whitelist ./whitelist.txt
[2020-08-06 22:56:15,211]    INFO Sorting BUS file tmp/output.s.c.bus to ./output.unfiltered.bus
[2020-08-06 22:56:17,545]    INFO Generating count matrix ./counts_unfiltered/cells_x_genes from BUS file ./output.unfiltered.bus
[2020-08-06 22:56:17,605]   ERROR An exception occurred
Traceback (most recent call last):
  File "/data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/kb_python/main.py", line 476, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/kb_python/main.py", line 148, in parse_count
    h5ad=args.h5ad,
  File "/data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/kb_python/count.py", line 453, in count
    bus_result['txnames'],
  File "/data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/kb_python/count.py", line 178, in bustools_count
    run_executable(command)
  File "/data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/kb_python/utils.py", line 114, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/data/homezvol0/gbalderr/anaconda3/lib/python3.7/site-packages/kb_python/bins/linux/bustools/bustools count -o ./counts_unfiltered/cells_x_genes -g kb_trial.txt -e ./matrix.ec -t ./transcripts.txt
 --genecounts ./output.unfiltered.bus' returned non-zero exit status 1.

I am not sure if I am missing something very obvious, but any clues on something I am doing wrong are welcome.

Thank you for your help!

Gaby B.

**Comment by GabyBG** [comment]
I figured out. The solution was the same as:
#63
