### ISSUE TITLE
Passing --make-unique argument into kb

### ISSUE THREAD

**Issue by axelalmet** [pachterlab/kb_python#97]
Dear kb team,

I am trying to build a reference using an axolotl genome, AmexG_v6.0-DD, from [this website](https://www.axolotl-omics.org/assemblies), and the corresponding annotation file, to quantify scRNA-seq data.

When I try to run the following command:
```
kb ref -i transcriptome_axolotl.idx -g t2g_axolotl.txt -f1 cdna_axolotl.fa \
AmexG_v6.0-DD.fa.gz \
AmexT_v47-AmexG_v6.0-DD.gtf.gz
```

I get this output (after passing `--verbose` but it was so long I dramatically shortened it):
```
[2021-02-14 18:04:16,288]   DEBUG Printing verbose output
[2021-02-14 18:04:16,288]   DEBUG kallisto binary located at /home/axela/.local/lib/python3.6/site-packages/kb_python/bins/linux/kallisto/kallisto
[2021-02-14 18:04:16,288]   DEBUG bustools binary located at /home/axela/.local/lib/python3.6/site-packages/kb_python/bins/linux/bustools/bustools
[2021-02-14 18:04:16,288]   DEBUG Creating tmp directory
[2021-02-14 18:04:16,288]   DEBUG Namespace(c1=None, c2=None, command='ref', d=None, f1='cdna_axolotl.fa', f2=None, fasta='AmexG_v6.0-DD.fa.gz', feature=None, flank=None, g='t2g_axolotl.txt', gtf='AmexT_v47-AmexG_v6.0-DD.gtf.gz', i='transcriptome_axolotl.idx', k=None, keep_tmp=False, lamanno=False, list=False, n=1, no_mismatches=False, overwrite=False, tmp=None, verbose=True, workflow='standard')
[2021-02-14 18:04:16,288]    INFO Preparing AmexG_v6.0-DD.fa.gz, AmexT_v47-AmexG_v6.0-DD.gtf.gz
[2021-02-14 18:04:16,288]    INFO Decompressing AmexT_v47-AmexG_v6.0-DD.gtf.gz to tmp
[2021-02-14 18:04:17,711]    INFO Creating transcript-to-gene mapping at /mnt/axela/scRNASeqData/axolotl/tmp/tmpt560t2dd
[2021-02-14 18:04:31,236]    INFO Decompressing AmexG_v6.0-DD.fa.gz to tmp
[2021-02-14 18:07:18,039]    INFO Sorting tmp/AmexG_v6.0-DD.fa to /mnt/axela/scRNASeqData/axolotl/tmp/tmp27hucco4
[2021-02-14 18:07:18,039]   DEBUG Found FASTA entry chr10p
...
[2021-02-14 18:59:59,712]    INFO Concatenating 1 transcript-to-gene mappings to t2g_axolotl.txt
[2021-02-14 18:59:59,780]    INFO Concatenating 1 cDNAs to cdna_axolotl.fa
[2021-02-14 19:00:00,451]    INFO Indexing cdna_axolotl.fa to transcriptome_axolotl.idx
[2021-02-14 19:00:00,452]   DEBUG kallisto index -i transcriptome_axolotl.idx -k 31 cdna_axolotl.fa
[2021-02-14 19:00:00,470]   DEBUG 
[2021-02-14 19:00:00,471]   DEBUG [build] loading fasta file cdna_axolotl.fa
[2021-02-14 19:00:00,471]   DEBUG [build] k-mer length: 31
[2021-02-14 19:00:00,471]   DEBUG Error: repeated name in FASTA file cdna_axolotl.fa
[2021-02-14 19:00:00,471]   DEBUG LOC111947635
[2021-02-14 19:00:00,471]   DEBUG 
[2021-02-14 19:00:00,471]   DEBUG Run with --make-unique to replace repeated names with unique names
[2021-02-14 19:00:00,471]   ERROR 
[build] loading fasta file cdna_axolotl.fa
[build] k-mer length: 31
Error: repeated name in FASTA file cdna_axolotl.fa
LOC111947635

Run with --make-unique to replace repeated names with unique names
[2021-02-14 19:00:00,471]   ERROR An exception occurred
Traceback (most recent call last):
  File "/home/axela/.local/lib/python3.6/site-packages/kb_python/main.py", line 785, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/axela/.local/lib/python3.6/site-packages/kb_python/main.py", line 159, in parse_ref
    temp_dir=temp_dir
  File "/home/axela/.local/lib/python3.6/site-packages/kb_python/ref.py", line 439, in ref
    cdna_fasta_path, index_path, k=k or 31
  File "/home/axela/.local/lib/python3.6/site-packages/kb_python/ref.py", line 212, in kallisto_index
    run_executable(command)
  File "/home/axela/.local/lib/python3.6/site-packages/kb_python/dry/__init__.py", line 24, in inner
    return func(*args, **kwargs)
  File "/home/axela/.local/lib/python3.6/site-packages/kb_python/utils.py", line 232, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/axela/.local/lib/python3.6/site-packages/kb_python/bins/linux/kallisto/kallisto index -i transcriptome_axolotl.idx -k 31 cdna_axolotl.fa' returned non-zero exit status 1.
[2021-02-14 19:00:00,480]   DEBUG Removing tmp directory

```
I understand that the argument `--make-unique` is passed to `kallisto index`, but I find that `kb ref` does not recognise this argument. I understand that I could run `kallisto index` directly, but I am unsure how to then generate the transcript-to-gene mapping file, i.e. `t2g_axolotl.txt`. Any advice on how to overcome this issue would be greatly appreciated. Thank you!

Best wishes,
Axel.

**Comment by Lioscro** [comment]
Hi, @axelalmet,

This is odd, as `kb ref` identifies a transcript by its transcript ID and version, so there should not be any duplicates in the generated transcriptome FASTA. Would it be possible to send over the FASTA and GTF you are using? That would greatly help in debugging & fixing this issue.

**Comment by Lioscro** [comment]
The issue is likely because the GTF contains spaces for transcript IDs. For instance, `LOC114595135 [nr]|ZNF268 [hs]|AMEX60DD201000002.1` is one such transcript ID. This is directly used as the FASTA sequence name, so in the case of our example, there will be a FASTA entry that starts with
```
>LOC114595135 [nr]|ZNF268 [hs]|AMEX60DD201000002.1
```
but the problem was that FASTA entries use space as the delimiter for different fields, so kallisto would interpret the above as a single entry with ID `LOC114595135`. You can see how this can lead to "duplicate" FASTA entries if there are multiple transcript IDs in the GTF that starts with `LOC114595135 ` but the rest of the ID differs.

I've pushed an update to the `devel` branch that should solve this issue by removing all spaces. It'd be great if you could try this out and let me know if if fixes the problem! You can install the `devel` branch with the following command.
```
pip install git+https://github.com/pachterlab/kb_python@devel
```

**Comment by axelalmet** [comment]
Hi @Lioscro, I can confirm that the update fixed everything! Thank you so much for your help and for addressing the issue so promptly!

I think we can close the issue now, now that everything works :).

Best wishes,
Axel.
